### ISSUE TITLE
Observed changes/regressions in 0.22.2 with pegdown-compatibility enabled

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#122]
I just updated to the 0.22.2 version, which fixes many of the HTML-block related issues we observed when updating from pegdown to flexmark.

Scanning our user entered markdown texts, I observed some changes when compared to 0.19.6

---
Image link not parsed anymore:
```
<div>
<a href="http://somelink.com/poster.pdf">

![Download Poster](http://someimg.com/poster.png)

</a>
</div>
```
**0.19.6 output**
```
<div> 
 <a href="http://somelink.com/poster.pdf"> <p><img src="http://someimg.com/poster.png" alt="Download Poster"></p> </a> 
</div>
```

**0.22.2 output**
```
<div>
<a href="http://somelink.com/poster.pdf">

![Download Poster](http://someimg.com/poster.png)

</a>
</div>
```
---
Indented HTML not parsed
```
<p>par</p>
    <ul>
      <li>list item</li>
    </ul>
```
**0.19.6 output**
```
<p>par</p> 
<ul> 
 <li>list item</li> 
</ul>
```

**0.22.2 output**
```
<p>par</p>
<pre><code>&lt;ul&gt;
  &lt;li&gt;list item&lt;/li&gt;
&lt;/ul&gt;
</code></pre>
```
---
The latter one seems to occur quite often, there are many indented HTML parts in the user-entered data.

**Comment by vsch** [comment]
@Elmervc, I will add indented HTML being treated as code to a test case because it is a bug.

The image not being parsed is because the default for pegdown now is to use pegdown rules which extend the HTML block until all tags are closed. I will put the defaults back to being less restrictive and create another `ParserEmulationProfile`, `PEGDOWN_STRICT` which will do the closer to pegdown HTML parsing emulation. This way it will be more backward compatible with previous versions of flexmark-java pegdown mode.

I'll make a release as soon as this is done but you may need to tweak the HTML deep parsing parameters to get "ideal" behaviour for your project. All these options can give "unexpected" results in some cases.

**Comment by vsch** [comment]
@Elmervc, default pegdown emulation now ends HTML block on a blank line. To disable this the strict version of settings should be used. Also added handling of optional end tags.

Repo updated, Maven update in progress.

**Comment by Elmervc** [comment]
@vsch Thanks for fixing this. We just switched from pegdown to flexmark-java (pegdown mode) in production and haven't seen noticable changes in renderings anymore. Most common issue we had to fix was bad HTML-code with missing closing tags, which Pegdown "fixed" by rendering the closing tag.

**Comment by vsch** [comment]
@Elmervc, you are welcome. How would you rate your overall experience migrating to flexmark-java from pegdown?

**Comment by Elmervc** [comment]
@vsch Main reason for us to switch were the performance issues with pegdown. We had a case where requests on some page took 10+ minutes to process the (for pegdown) problematic markdown text, not freeing resources during that period. Flexmark-java was advertised and is/was the best choice for replacement, which also supports all extensions pegdown provided.

I think there were only few users who started using flexmark-java as pegdown replacement at the moment we decided to switch. There wasn't yet much feedback on such migrations/not much real-world data tested. We found out there were some noticable differences in rendering, occurring frequently in our user-data. Some time was spent on writing analysis code* to scan all user-entered texts for markdown code/HTML code that did not render as intended by the user. This revealed some issues for which you provided fixes, most of them within a day (chapeau!). Most of them were related to HTML blocks. Now that these issues are fixed, I expect new users of flexmark-java who migrate from pegdown don't need to put in much effort. Still, there will be some cases where pegdown parses/renders parts differently, because of flexmark-java being more strict (iow: pegdown lacking actual specs/having inconsistencies).

* This code mainly renders all markdown texts and scans the rendered HTML using regex for occurrences of `]\s*(` (unparsed links) `/&lt;.*&gt;/` (unparsed HTML), `\s(\*|_)\S.*(\*|_)` (unparsed bold/italics) and `^#` (unparsed headers).

Overall, it took a bit more effort for us than expected to migrate to flexmark-java, caused by some pegdown-specific processing behavior which was missing. But there is definitely no better alternative and new users will experience a smoother migration.

**Comment by vsch** [comment]
@Elmervc, thank you for the detailed description. Previous experience with "emulators" taught me that to be a seamless replacement a system needs to duplicate undocumented behaviour because users determine their input by trial and error which includes implementation caused behaviours and bugs.

I am sure new user content will not suffer from pegdown peculiarities because they will use trial and error to get the results they want, this time with flexmark-java idiosyncrasies.
