### ISSUE TITLE
Feature: Adding source line numbers to nodes

### ISSUE THREAD

**Issue by wouterd** [vsch/flexmark-java#130]
Thanks for the great library. We've been using it to parse Markdown files that we use to configure our infrastructure.

What I need for error reporting is line numbers and I've written een utility method to figure them out for a node. Would it make sense to add this functionality to nodes themselves?

See code below:
```
    static int getLineNumber(Node node) {
        BasedSequence preText = node.getChars().baseSubSequence(0, node.getStartOffset());
        if (preText.isEmpty()) return 1;
        int lineNumber = 1;
        int nextLineEnd = preText.endOfLineAnyEOL(0);
        while (nextLineEnd < preText.length()) {
            lineNumber++;
            nextLineEnd = preText.endOfLineAnyEOL(nextLineEnd + 1);
        }
        return preText.lastChar() == '\n' ? lineNumber : lineNumber + 1;
    }
```

**Comment by vsch** [comment]
@wouterd, good idea.

I added the following line number API, which gives you the above but by using available internal line structures, so it steps through the line segment array list instead of scanning the text again. You need to add the parser option to track document lines. I did not want to add this storage overhead by default for those that don't need it.

* Add: `Parser.TRACK_DOCUMENT_LINES` default `false`. When `true` document lines are tracked in
  the document's `lineSegments` list and offset to line method can be used to get the 0-based
  line number for the given offset. When `false` these functions return `0`.

* Add: line number API functions to `Node` and `Document`, set`Parser.TRACK_DOCUMENT_LINES` to
  true to have these functions return other than 0.

  * `Node.getLineNumber()` and `Node.getStartLineNumber()` returns 0-based line number for
    node's start offset.

  * `Node.getEndLineNumber()` returns 0-based line number for node's end offset - 1.

  * `Document.getLineCount()` returns number of lines in the document

  * `Document.getLineNumber(int offset)` returns 0-based line number for the given offset or
    `Document.getLineCount()` if offset is outside the document text range.

I will be making a release shortly

**Comment by vsch** [comment]
@wouterd, version 0.22.14 released. repo updated, maven update in progress.

**Comment by wouterd** [comment]
Thanks for the quick response, it works like a charm and all my tests still pass. 👍 

Did you go for 0-based for a reason? I'm +1'ing that answer everywhere now, because that's the line numbers people see in their text editors.

**Comment by vsch** [comment]
@wouterd, it is 0-based to keep with the Java index convention, but other than that no other reason. I will probably expose the document lines array through the API, then the line number will be an index into this array.

**Comment by wouterd** [comment]
Ah, that makes sense then. You could expose both LineIndex and LineNumber, but that might be confusing as well. hmm. :)

**Comment by vsch** [comment]
@wouterd, just realized that the lines are already part of the API for `Document` from its `ContentBlock` inheritance.

You can use `getLineChars(int lineNumber)` returns the char sequence for the 0-based line number.

**Comment by vsch** [comment]
@wouterd, more thought about the current implementation led me to realize that it is best to allow `Document.getLineNumber(int offset)` to return line number when  `Parser.TRACK_DOCUMENT_LINES` is false. In this case it is less efficient because it counts EOL in document char  sequence, every time but when line number is needed for error reporting, this works without incurring storage   overhead of storing individual line character sequences.

I made changes for the next release to fall back to your code adjusted for 0-based line number. You will be able to leave `Parser.TRACK_DOCUMENT_LINES` set to its default value and still get the line number for the node.

**Comment by vsch** [comment]
Repo updated. Maven updated. Now you don't need to enable line tracking if you only need it for error reporting and don't want to incur the storage overhead for every line in every document.
