### ISSUE TITLE
[Question] What's the easiest way to disable rendering intended text as code?

### ISSUE THREAD

**Issue by sladkoff** [vsch/flexmark-java#134]
I'd like to disable rendering the following as code:

```
    this text is inteded with four spaces
```

Note I still want to be able to render this as code:

````
~~~
Code block via tilde
~~~
```
Code block via quotes
```
````

I didn't find any options for this? What would be the easiest / most *out-of-the-box* way to solve this?

Thank you.

**Comment by vsch** [comment]
@sladkoff, the setting that controls indented code used throughout the library in `Parsing.CODE_BLOCK_INDENT` is set from the `Parser.LISTS_ITEM_INDENT` option value ([Parsing.java](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/ast/util/Parsing.java#L174-L176)). So you can change the latter value. Keep in mind that it will also affect indentation of list items. Text that would be treated as indented code will now be considered a list item or paragraph.

However, if you set it to 8 instead of the standard 4 set by all families then indented code blocks will start when 8 or more spaces are used.

I suggest you do some testing to see the side-effects of changing this to a higher value.

**Comment by sladkoff** [comment]
@vsch Thank you for the feedback. My problem was with parsing template files with existing indentation, which became formatted as code. I didn't want to change the list item indent globally right now, so I removed the spaces in the files for now.

Is there a reason why you can't change `Parsing.CODE_BLOCK_INDENT` independently of `Parsing.LIST_ITEM_INDENT`? Would it make sense to add a separate option for the code indent in the future?

**Comment by vsch** [comment]
@sladkoff, I can split them and create a separate option for `CODE_BLOCK_INDENT` that inherits from `LIST_ITEM_INDENT` meaning the former will have the value of the later, unless it is explicitly provided. 

I'll make the change and make a release so you can see if it will solve your particular use case issues.

**Comment by vsch** [comment]
@sladkoff, repo updated. Maven update in progress.

**Comment by sladkoff** [comment]
@vsch I tried the new version but unfortunately that doesn't help in my particular use case.

I'm sorry for bothering you as this has nothing to do with the library but with the indentation of our files. 

If you're curious, here's an example of what's happening, even with `CODE_BLOCK_INDENT` set to something high:

```
<#-- This is a Freemarker template file -->
<body>
    <div>
        <#-- Note: content inside this tag is parsed and rendered as markdown... -->
        <@customMarkdownMacro>
           <#-- This is variable holding the raw markdown, note the indentation before the variable -->
            ${userGeneratedMarkdown}
        </@customMarkdownMacro>
    <div>
</body>
```

Now, assume `userGeneratedMardkown = '### Headline 3'`

Although `CODE_BLOCK_INDENT` is set to 999 (disabled) and the markdown is not rendered as code block (as I wanted in the previous question), it is still not rendered as headline in this case because it's parsed with the trailing white spaces.

So the solution for us is still to trim the white spaces in our template files manually.

I still think it's nice that you can change the `CODE_BLOCK_INDENT` separately now.

Thanks for the help.
