### ISSUE TITLE
Render problem when  there is a line below the table 

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#135]
Hi,@vsch.
I found the text：
```
|a|b|c|
|---|---|---|
|1|2|3|
---
```
It can't be rendered because of the diving line 
Could you solve this problem？

**Comment by vsch** [comment]
@Hxuhao233, this happens because table processing occurs right before inline processing and only on paragraph blocks.

The `---` causes the previous lines to be interpreted as a level 2 heading and  `===` would cause it to be a level 1 heading. These are the only character sequences that would cause the table not to be recognized since these are the only post fix markers for preceding lines.

The old implementation of tables in the `flexmark-ext-gfm-tables` module parses the lines during  block recognition and will parse the above markdown as you expect. However, it has more limitations in table parsing and will only parse tables with GFM limitations.

The only solution for the `flexmark-ext-tables` module is to include a blank line between the table and the following text if it can be interpreted as a level 1 or level 2 heading.

**Comment by Hxuhao233** [comment]
Sorry,@vsch, I was so late to reply.
So,i should include a blank line to render it correctly.
I get it.Thank you!
