### ISSUE TITLE
How to migrate a custom pegdown extension to flexmark

### ISSUE THREAD

**Issue by zjffdu** [vsch/flexmark-java#139]
First sorry if this is not the right place to ask question. I didn't find other proper place to ask. 
I want to migrate my project from pegdown to flexmark. But I have some custom pegdown extension in my project. How can I still use these custom extension in my project ? Thanks

**Comment by vsch** [comment]
@zjffdu, flexmark-java parser architecture differs from pegdown, this is what makes it so much faster but it does require that pegdown extensions be re-implemented. The difficulty depends on what exactly your extension does. Overview docs in the wiki [Writing Extensions](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions)

**Q: Can you be more specific about what your extension does? For example LinkRenderer, parser extensions, HTML renderer, etc.**

There are a few samples in the [`flexmark-java-samples`](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples), including pegdown options adapter, link resolver, node renderer, attribute provider for customizing HTML attributes.

All the extension modules can also be a source of inspiration since all extras beyond the CommonMark Spec 0.27 are implemented as extensions and can be used as a starting point for your customizations. Description in the wiki [Extensions](https://github.com/vsch/flexmark-java/wiki/Extensions)
