### ISSUE TITLE
Artifact missing on Maven

### ISSUE THREAD

**Issue by chipsenkbeil** [vsch/flexmark-java#141]
I'm not able to grab flexmark-java because it appears to be missing from Maven Central.

Was trying to grab 0.22.22, which seems to be the latest on Maven, but...

- This jar is missing https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.22.22/flexmark-java-0.22.22.jar
    - You can see only the pom and some other artifacts are found under https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.22.22/
- Jars like https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.22.22/flexmark-util-0.22.22.jar exist
    - You can see the jar, javadoc, etc. are all found under https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.22.22/

The missing artifacts for flexmark-java seem to be the case for every single version, but I had used an earlier version in the past without issue. Now, I can't get flexmark-java at all. Am I missing something?

**Comment by vsch** [comment]
flexmark-java is the parent project for all the modules and artifacts and does not have its own jar file.

If you want all modules (except the `flexmark-ext-spec-example` which has a run-time dependency on `flexmark-test-util` and hence on junit) then you should use the `flexmark-all` artifact, otherwise you can include only those module that you need.

**Comment by chipsenkbeil** [comment]
Thanks, that cleared it up. Not sure how I had it working before. Switching from `flexmark-java` to just `flexmark` and including the other modules like I was doing earlier fixed my issue.
