### ISSUE TITLE
FlexmarkHtmlParser builders not static

### ISSUE THREAD

**Issue by GomiGuchi** [vsch/flexmark-java#143]
There is no way to get an instance of FlexmarkHtmlParser for further customization. There are two public build methods, but neither one is static and the constructor of the class is private.

Unless there is a reason not to, I think the builders should be static.

**Comment by vsch** [comment]
@GomiGuchi, thanks for catching and fixing it. However, keep in mind that the html parser instance caches the values from options so if you getOptions() and modify them, the parser will continue to use its cached values.

I will be making a release shortly.

**Comment by vsch** [comment]
@GomiGuchi, ignore previous comment. The only value you can change is Trace flag for debugging.

I made a change to allow re-use of parser instance, now resets internal state before a parse so that the same instance can be used for parsing multiple HTML strings, sequentially.

Repo updated. Maven update in progress.

**Comment by GomiGuchi** [comment]
@vsch Thanks for thinking of reuse! I will be passing a lot of strings in one go, so that is very handy.

The reason I want access to the instance is for using a customized `FormattingAppendable`

**Comment by vsch** [comment]
@GomiGuchi, my pleasure. 

During initial implementation I was more concerned with getting it to work and afterwards moved on without doing a clean up. Thank you for bringing it to my attention.
