### ISSUE TITLE
Support for Reddit's version of superscript

### ISSUE THREAD

**Issue by Saketme** [vsch/flexmark-java#164]
Hello, I just noticed that Reddit uses a different syntax for superscript. Instead of using a closing marker, it simply checks for a whitespace.

Current syntax: `^superscript^`.
Reddit's syntax: `^superscript`.

Reddit also lets you nest multiple superscripts this way: `N^o^o^o^o^o^o`

I'm trying to modify the superscript extension and I replaced the closing character with a whitespace (`' '`), but I cannot figure out where to go next from here. Will someone be able to suggest what other modifications do I need to make?

**Comment by vsch** [comment]
@Saketme, you cannot implement this feature using delimited text because in this case it is not delimited.

You would need to write an inline parsing extension that handles it.

[`flexmark-ext-xwiki-macros`](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-xwiki-macros/src/main/java/com/vladsch/flexmark/ext/xwiki/macros/internal/MacroInlineParser.java) does its own parsing of inline macros and you can see how it does it as a start.

**Comment by Saketme** [comment]
Got it, thanks!
