### ISSUE TITLE
IndentedCodeBlock endOffset too large?

### ISSUE THREAD

**Issue by JFormDesigner** [vsch/flexmark-java#17]
I think the endOffset of `IndentedCodeBlock` is too large. It is at the start of the next paragraph, so the `IndentedCodeBlock` includes trailing line separators and empty lines.

On the other hand,  the end offset in `FencedCodeBlock` does not include trailing line separators and empty lines.

```java
String markdown = "\tcode\n\nsome text";

Parser parser = Parser.builder().build();
Node document = parser.parse(markdown);
System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
```
Outputs:
```
Document[0, 16]
  IndentedCodeBlock[1, 7]
  Paragraph[7, 16]
    Text[7, 16] chars:[7, 16, "some text"]
```

Shouldn't the `IndentedCodeBlock` end at `5` ?

**Comment by vsch** [comment]
@JFormDesigner, it is a bug. It should only include the `\n` after the last line. I did not notice because my plugin was using pegdown and its AST needed a lot of massaging so the plugin already had code to strip off trailing blank lines from indented code ranges.

How critical are the last few bugs you reported to your effort? Do you need a fix ASAP or can it take another couple of days?

**Comment by JFormDesigner** [comment]
> How critical are the last few bugs you reported to your effort? Do you need a fix ASAP or can it take another couple of days?

None of the few bugs is critical. Take your time 😉

**Comment by vsch** [comment]
I added an option to the `Parser.INDENTED_CODE_NO_TRAILING_BLANK_LINES` that by default is `true` and will trim the trailing white space. If `false` will leave it as it is now.
