### ISSUE TITLE
Markdown parser converting some text into links even though it dosen't link anywhere

### ISSUE THREAD

**Issue by paladox** [vsch/flexmark-java#173]
Hi, i've noticed in the flexmark-java parser it is making some sections a hyperlink even though it dosen't have a url that once click redirects to.

See

<img width="1439" alt="screen shot 2017-11-06 at 13 26 03" src="https://user-images.githubusercontent.com/5727000/32443227-2b3697fa-c2f6-11e7-9d59-1d07967de42c.png">

<img width="1440" alt="screen shot 2017-11-06 at 13 26 44" src="https://user-images.githubusercontent.com/5727000/32443236-2f5bd764-c2f6-11e7-86d8-6f2360302716.png">

It seems it is adding <a> twice.

In the old parser it didnt make "download.command" a hyper link and same for "Section download"

This is the md file https://gerrit.googlesource.com/plugins/download-commands/+show/refs/heads/master/src/main/resources/Documentation/config.md

**Comment by vsch** [comment]
@paladox, how can I get a link to a raw file. This link shows the file content massaged for HTML. I need raw unaltered text to figure out what is going on.

**Comment by vsch** [comment]
@paladox, the generated markdown is:

```markdown
### <a id="download">Section download</a>
```

which has an embedded inline anchor for the heading text. Then the options for HTML serialization have ANCHORLINKS extension enabled which wraps the text in an anchor.

The generated markdown appears to be highly dependent on pegdown peculiarities in parsing and generating HTML. 

I think it would be a good idea to review the generated Markdown and clean it up to generate Markdown or even better CommonMark since the latter has a specification.

**Comment by paladox** [comment]
@vsch hi, here https://gerrit.googlesource.com/plugins/download-commands/+show/refs/heads/master/src/main/resources/Documentation/config.md
