### ISSUE TITLE
YouTubeLinkSample seems not to work

### ISSUE THREAD

**Issue by bvn13** [vsch/flexmark-java#174]
[This example](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/YouTubeLinkSample.java) seems not work at all.

I use it as:
``` java

    public String renderToHtml(String content) {

        MutableDataSet options = new MutableDataSet();

        // uncomment to set optional extensions
        options.set(Parser.EXTENSIONS, Arrays.asList(
                TablesExtension.create(),
                StrikethroughExtension.create(),
                YoutubeLinkTransformer.YouTubeLinkExtension.create()
        ));

        // uncomment to convert soft-breaks to hard breaks
        //options.set(HtmlRenderer.SOFT_BREAK, "<br />\n");

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        // You can re-use parser and renderer instances
        Node document = parser.parse(content);
        String html = renderer.render(document);  // "<p>This is <em>Sparta</em></p>\n"

        return html;
    }

```

and when I try to parse test text 
```
[test](https://www.youtube.com/watch?v=GYem-BGEhaY) 

```

nothing happens.

**Comment by bvn13** [comment]
Seems I was able to fix it. Here is the whole class of exrtension:

``` java
package com.raysmond.blog.support.web.extensions;

import com.vladsch.flexmark.Extension;
import com.vladsch.flexmark.ast.*;
import com.vladsch.flexmark.html.CustomNodeRenderer;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.html.HtmlWriter;
import com.vladsch.flexmark.html.renderer.*;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.parser.block.NodePostProcessor;
import com.vladsch.flexmark.parser.block.NodePostProcessorFactory;
import com.vladsch.flexmark.util.NodeTracker;
import com.vladsch.flexmark.util.options.DataHolder;
import com.vladsch.flexmark.util.options.MutableDataHolder;
import com.vladsch.flexmark.util.sequence.BasedSequence;

import java.util.HashSet;
import java.util.Set;

public class YoutubeLinkTransformer {

    public static class YouTubeLink extends InlineLinkNode {
        public YouTubeLink() {
        }

        public YouTubeLink(final Link other) {
            super(other.getChars().baseSubSequence(other.getChars().getStartOffset() - 1, other.getChars().getEndOffset()),
                    other.getChars().baseSubSequence(other.getChars().getStartOffset() - 1, other.getTextOpeningMarker().getEndOffset()),
                    other.getText(),
                    other.getTextClosingMarker(),
                    other.getLinkOpeningMarker(),
                    other.getUrl(),
                    other.getTitleOpeningMarker(),
                    other.getTitle(),
                    other.getTitleClosingMarker(),
                    other.getLinkClosingMarker()
            );
        }

        @Override
        public void setTextChars(final BasedSequence textChars) {
            int textCharsLength = textChars.length();
            this.textOpeningMarker = textChars.subSequence(0, 1);
            this.text = textChars.subSequence(1, textCharsLength - 1).trim();
            this.textClosingMarker = textChars.subSequence(textCharsLength - 1, textCharsLength);
        }
    }

    public static class YouTubeLinkNodePostProcessor extends NodePostProcessor {
        public YouTubeLinkNodePostProcessor(DataHolder options) {
        }

        @Override
        public void process(NodeTracker state, Node node) {
            if (node instanceof Link) {
                Node previous = node.getPrevious();

                if (previous instanceof Text) {
                    final BasedSequence chars = previous.getChars();
                    if (chars.endsWith("@") && chars.isContinuedBy(node.getChars())) {
                        // trim previous chars to remove '@'
                        previous.setChars(chars.subSequence(0, chars.length() - 1));

                        YouTubeLink youTubeLink = new YouTubeLink((Link) node);
                        youTubeLink.takeChildren(node);
                        node.unlink();
                        previous.insertAfter(youTubeLink);
                        state.nodeRemoved(node);
                        state.nodeAddedWithChildren(youTubeLink);
                    }
                }
            }
        }

        public static class Factory extends NodePostProcessorFactory {
            public Factory(DataHolder options) {
                super(false);

                addNodes(Link.class);
            }

            @Override
            public NodePostProcessor create(Document document) {
                return new YouTubeLinkNodePostProcessor(document);
            }
        }
    }

    public static class YouTubeLinkNodeRenderer implements NodeRenderer {

        public YouTubeLinkNodeRenderer(DataHolder options) {
        }

        @Override
        public Set<NodeRenderingHandler<?>> getNodeRenderingHandlers() {
            final YouTubeLinkNodeRenderer self = this;

            HashSet<NodeRenderingHandler<?>> set = new HashSet<NodeRenderingHandler<?>>();
            set.add(new NodeRenderingHandler<Link>(Link.class, new CustomNodeRenderer<Link>() {
                @Override
                public void render(Link node, NodeRendererContext context, HtmlWriter html) {
                    self.render(node, context, html);
                }
            }));
            return set;
        }

        private void render(final Link node, final NodeRendererContext context, final HtmlWriter html) {
            if (context.isDoNotRenderLinks()) {
                context.renderChildren(node);
            } else {
                // standard Link Rendering
                ResolvedLink resolvedLink = context.resolveLink(LinkType.LINK, node.getUrl().unescape(), null);

                if (resolvedLink.getUrl().contains("www.youtube.com/watch")) {

                    html.attr("src", resolvedLink.getUrl().replace("watch?v=", "embed/"));
                    html.attr("width", "420");
                    html.attr("height", "315");
                    html.attr("class", "youtube-embedded");
                    html.srcPos(node.getChars()).withAttr(resolvedLink).tag("iframe");
                    //context.renderChildren(node);
                    html.tag("/iframe");

                } else {
                    html.attr("href", resolvedLink.getUrl());
                    if (node.getTitle().isNotNull()) {
                        html.attr("title", node.getTitle().unescape());
                    }
                    html.srcPos(node.getChars()).withAttr(resolvedLink).tag("a");
                    context.renderChildren(node);
                    html.tag("/a");
                }

            }
        }

        public static class Factory implements NodeRendererFactory {
            @Override
            public NodeRenderer create(final DataHolder options) {
                return new YouTubeLinkNodeRenderer(options);
            }
        }
    }

    public static class YouTubeLinkExtension implements Parser.ParserExtension, HtmlRenderer.HtmlRendererExtension {
        private YouTubeLinkExtension() {
        }

        public static Extension create() {
            return new YouTubeLinkExtension();
        }

        @Override
        public void extend(Parser.Builder parserBuilder) {
            parserBuilder.postProcessorFactory(new YouTubeLinkNodePostProcessor.Factory(parserBuilder));
        }

        @Override
        public void rendererOptions(final MutableDataHolder options) {

        }

        @Override
        public void parserOptions(final MutableDataHolder options) {

        }

        @Override
        public void extend(HtmlRenderer.Builder rendererBuilder, String rendererType) {
            if (rendererType.equals("HTML")) {
                rendererBuilder.nodeRendererFactory(new YouTubeLinkNodeRenderer.Factory());
            } else if (rendererType.equals("JIRA") || rendererType.equals("YOUTRACK")) {
            }
        }
    }

}

```

Could you include it into Extensions library? I changed type of Node from YouTubeLink to Link and wrote link-to-embedded-iframe converter.

``` java
public Set<NodeRenderingHandler<?>> getNodeRenderingHandlers() {
            final YouTubeLinkNodeRenderer self = this;

            HashSet<NodeRenderingHandler<?>> set = new HashSet<NodeRenderingHandler<?>>();
            set.add(new NodeRenderingHandler<Link>(Link.class, new CustomNodeRenderer<Link>() {
                @Override
                public void render(Link node, NodeRendererContext context, HtmlWriter html) {
                    self.render(node, context, html);
                }
            }));
            return set;
        }
```

**Comment by vsch** [comment]
@bvn13, thank you for your contribution. I will merge it shortly and make a release.

**Comment by vsch** [comment]
@bvn13, I split out the code into individual classes to match the layout and format of other extensions. I also added test class and a single test for the conversion.

Version 0.28.8. Repo was updated. Maven release is done but may take time to show up in the index.

You will need to change your code since the extension class was moved to its own file.

Thank you very much for taking the time to add to the library. It is very much appreciated.

**Comment by bvn13** [comment]
I'm glad to contribute to the library :)

Could you explain me where and how does the parsing work? I cannot find out the code which it determines chars sequences converting into classes.

**Comment by vsch** [comment]
@bvn13, the parser is based on the CommonMark parser architecture. The description can be found in the spec http://spec.commonmark.org/0.28/#appendix-a-parsing-strategy

**Comment by bvn13** [comment]
@vsch I could say incorrectly. I mean that in case of link: there is text template '[]()' determining a link. Where can I find that code which is parsing the whole text and creates Link class from this template. What should I do if I want to implement new text template (not used yet, i.e. simething like $$$)?

**Comment by vsch** [comment]
@bvn13, link being an inline element the logic for parsing this is found in the InlineParser. 

The API for extending this is also part of the InlineParser. You can take a look at some extensions which use the inline parser extension API. There are several flavours of extensions depending on the syntax of the new element.

An overview of the parsing process and various phases is covered in [Writing-Extensions](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions)

![Flexmark Parsing](https://github.com/vsch/flexmark-java/raw/master/assets/images/flexmark-parsing.png)

There is no simple template for parsing elements. Block parsing architecture is the hardest to wrap your head around. I must admit it still takes me a while to figure out how to handle what I want in the code. Inline parsing is a little easier but still complex. Especially, since I had to add extension points into the API to allow efficient implementation of inline extensions.

Examples of various uses are in the extensions.

### Delimiter processing 

These use delimited text with start and end character to delimit elements.

[EmojiExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-emoji/src/main/java/com/vladsch/flexmark/ext/emoji/EmojiExtension.java)

[InsExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-ins/src/main/java/com/vladsch/flexmark/ext/ins/InsExtension.java)

[StrikethroughExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-strikethrough/src/main/java/com/vladsch/flexmark/ext/gfm/strikethrough/StrikethroughExtension.java)

### LinkRefProcessor extension

These add elements which would normally be interpreted as references `![]` or `[]` including nested square brackets such as `[[]]` and `![[]]` which is used by wiki links, or `[^id]` which is used by footnotes.

[WikiLinkExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-wikilink/src/main/java/com/vladsch/flexmark/ext/wikilink/WikiLinkExtension.java)

[FootnoteExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-footnotes/src/main/java/com/vladsch/flexmark/ext/footnotes/FootnoteExtension.java)

### Inline Parser Extension

These use arbitrary text parsing to create custom elements.

[GfmIssuesExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-issues/src/main/java/com/vladsch/flexmark/ext/gfm/issues/GfmIssuesExtension.java)

[GfmUsersExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-users/src/main/java/com/vladsch/flexmark/ext/gfm/users/GfmUsersExtension.java)

[Xwiki Macros Extension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-xwiki-macros/src/main/java/com/vladsch/flexmark/ext/xwiki/macros/MacroExtension.java)


### Paragraph Processor extension

These "pre-process" paragraph blocks before they are passed to the inline parser for processing to extract leading element definitions. This is the same mechanism used by standard commonmark parser to extract reference definitions from beginning of paragraphs. 

[AbbreviationExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-abbreviation/src/main/java/com/vladsch/flexmark/ext/abbreviation/AbbreviationExtension.java)

### Block Pre-Processor Extension

These process parsed blocks before they are parsed for inline content.

[DefinitionExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-definition/src/main/java/com/vladsch/flexmark/ext/definition/DefinitionExtension.java)

[TaskListExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-tasklist/src/main/java/com/vladsch/flexmark/ext/gfm/tasklist/TaskListExtension.java)

### Post Processor Extension

These do not modify the parser process and instead manipulate the resulting AST to modify the AST removing and adding their custom nodes based on the content parsed by standard parsing.

[AutolinkExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-autolink/src/main/java/com/vladsch/flexmark/ext/autolink/AutolinkExtension.java)

[EscapedCharacterExtension](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-escaped-character/src/main/java/com/vladsch/flexmark/ext/escaped/character/EscapedCharacterExtension.java)

[SyntheticLinkSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/SyntheticLinkSample.java)
