### ISSUE TITLE
docx-converter pandoc emulation mode

### ISSUE THREAD

**Issue by bk1te** [vsch/flexmark-java#176]
Hello, thanks for all your work you have done!
Using your project I'm trying to create report from user input formated in markdown. I spent several days trying to generate docx file from resulted markdown 

```markdown
### header
1. List item started from 1
### header 
1. List item started from 1
1. List item continued 2
### test
1. List item started from 1
```

docx-converter rendered this markdown with one list with continiues numbering and strange styling

I tried to convert generated markdown with pandoc, and i get what i want,  correct list numbering and smooth styling

Is there any examples or article how to style generated docx ?? Or is it possible to style like pandoc did.
Thanks.

**Comment by vsch** [comment]
@bk1te, the conversion code sample is best taken from the test case which shows options explicitly while the sample code [DocxConverterPegdown](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/DocxConverterPegdown.java) uses pegdown options adapter out of laziness.

I added a commonmark version so that the markdown parsing options match commonmark in [DocxConverterCommonMark](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/DocxConverterCommonMark.java)

The markdown parsing options should match the markdown syntax. The AST node for the document will then be rendered by the DocX renderer.


Here is the result of running your markdown sample through the sample:

![image](https://user-images.githubusercontent.com/10299086/33188244-5ec3df92-d066-11e7-9ad7-5708a621b53d.png)

**Comment by vsch** [comment]
@bk1te, the formatting of the docx document is taken from the styles in the document package passed to the renderer. The default document is taken from [empty.xml](https://github.com/vsch/flexmark-java/blob/master/flexmark-docx-converter/src/main/resources/empty.xml) 

You can look at the styles defined in the empty document above or take a document generated by the converter and change the styles to your liking, delete all text and save the empty document. You can then use the empty document to pass to the `DocxRenderer` which will then use this is empty document to populate with converted markdown.

Here is an example of using an existing document as the template for conversion:

```java
InputStream emptyTemplate = new FileInputStream(emptyTemplatePath);
WordprocessingMLPackage mlPackage = DocxRenderer.getDefaultTemplate(emptyTemplate);
docxRenderer.render(document, mlPackage);
mlPackage.save(docxFile, Docx4J.FLAG_SAVE_ZIP_FILE);
```

`document` is the markdown `Document` node returned by the parser.

**Comment by bk1te** [comment]
Just created new maven project at [https://github.com/bk1te/flexmark] run it and what have i got
![shot-2017-11-24_20-07-55](https://user-images.githubusercontent.com/1233456/33223442-696f95cc-d12d-11e7-9854-dd43aa201fca.jpg)

**Comment by vsch** [comment]
@bk1te, the issue seems that Word handles the generated docx but LibreOffice does not.

I will take a look at what LibreOffice generates and what it expects.

**Comment by vsch** [comment]
@bk1te, fixed. version 0.28.10

Word DOCX only needs a new numbered list numID to be used on the first list item or on an item that changes the numbering, subsequent items use the default numID. LibreOffice expects the numID to be used on all items of a given list.

Repo updated. Maven update in progress.

**Comment by bk1te** [comment]
Thanks.
Afterall I want from this source [sample.txt](https://gist.github.com/bk1te/0aec2ff16ee6423f74d71a67496f9ff3) 
get this output
![shot-2017-11-25_06-39-41](https://user-images.githubusercontent.com/1233456/33228300-9f7936e8-d185-11e7-9e71-17a712051c9b.jpg)
With provided defaults i got
![shot-2017-11-25_06-51-26](https://user-images.githubusercontent.com/1233456/33228357-29a13acc-d187-11e7-8aa9-8c48be418746.jpg)
With ParserEmulationProfile.FIXED_INDENT.getProfileOptions() instead of new MutableDataSet()
I get what I want! Thanks!
Next on my plan is document styling...

**Comment by bk1te** [comment]
Using blank docx (generated by libreoffice or word) or pandoc reference.docx
`template = DocxRenderer.getDefaultTemplate(new FileInputStream("/usr/share/pandoc/data/reference.docx"));`
results in stacktrace: 
`
Exception in thread "main" org.docx4j.openpackaging.exceptions.InvalidOperationException: List 3 does not exist
	at org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.restart(NumberingDefinitionsPart.java:220)
	at com.vladsch.flexmark.docx.converter.internal.CoreNodeDocxRenderer.renderListItem(CoreNodeDocxRenderer.java:619)
	at com.vladsch.flexmark.docx.converter.internal.CoreNodeDocxRenderer.render(CoreNodeDocxRenderer.java:602)
	at com.vladsch.flexmark.docx.converter.internal.CoreNodeDocxRenderer.access$3100(CoreNodeDocxRenderer.java:56)
	at com.vladsch.flexmark.docx.converter.internal.CoreNodeDocxRenderer$33.render(CoreNodeDocxRenderer.java:354)
`

**Comment by vsch** [comment]
@bk1te, the blank document should have the styles which are used by the docx converter. It assumes that the default styles are already defined.

It appears that your document does not have the standard styles for lists.

You should use the default empty template in the docx module to create an empty document which you can then open and modify its styles.

**Comment by bk1te** [comment]
I thought like you said. 
I create docx from generated markdown with getDefaultTemplate()
Restyle: Change font, alignment, spacing and saved as template.docx (with contents)
use it as template, in resulted doc i had content from first run and after that with second.
If i removed content from template and save changes. after using it no restyling applied to my content.

**Comment by vsch** [comment]
@bk1te, I will have to see if LibreOffice does not save styles for an empty document.

The other option is to modify the styles in empty.xml and pass it to template.

Another way is to open a template with content but to delete the content before passing it to render().

DOCX format is a mess to use with a lot of nuances and dependencies. I work with it by google, trial and error.

**Comment by bk1te** [comment]
is ODT better?

**Comment by bk1te** [comment]
I tried to edit empty.xml, but everything I can change there is "font type", can`t find how to change page size and margins, can`t find how to add heading... no generic templates for creating empty.xml

**Comment by vsch** [comment]
@bk1te, I don't know if ODT is better. Although since ODT was created as an open compatible format it probably inherited the DOCX hassles.

The format is very verbose and very finicky.

As for creating header/footer and manipulating document properties those will need to be done through the docx4java API. https://github.com/plutext/docx4j

I am now wrestling with trying to add content to an existing document but found that docx4j can't even open the original and save it to another file while replacing some text content. The file opens in OfficeLibre but not in Word.

It seems that there is a need to do a deep copy of all the content from one to the other, with all the relationships recreated, and this requires much deeper understanding of DOCX that I have or willing to invest time learning.

**Comment by bk1te** [comment]
BTW same error with ordering list, list across document

**Comment by bk1te** [comment]
Sorry no ordered but bullet list

**Comment by vsch** [comment]
@bk1te, what do you mean by "the same with bullet list across document"?

Bullet list items do not have order numbering. Can you give a bit more detail please.

**Comment by bk1te** [comment]
Sub bullet lists should break on new top level list element, but for now they did'not just like ordered list did, before you fix. So for many ordered lists across the document, there is one continiuos bullet list.

**Comment by bk1te** [comment]
For now i stop using docx converter in favour of using flexmark to preprocess markdown and pass formatted markdown file to pandoc.
Is there any links how to format ast as pandoc specific markdown version http://pandoc.org/MANUAL.html#pandocs-markdown

**Comment by bk1te** [comment]
FYI pandoc docx generation sucks to, I stoped at ODT

**Comment by vsch** [comment]
@bk1te, from what I saw pandoc is a fixed indent processor so the closest parsing behavior is probably pegdown. 

I have not spent time on fine tuning parser options specifically for pandoc. It literally takes days to figure out all the parsing differences and in the end some idiosyncrasies cannot be duplicated in flexmark-parser architecture. These usually have to do with how the parsers handle edge cases.

As for a bullet list being one long list, I will address it. It is an oversight on my part. New lists are started only for numeric lists since the order affects the result. Bullet lists are not restarted.

**Comment by vsch** [comment]
@bk1te, forgot to mention that there is an example of converting pegdown to common mark in the PegdownToCommonMark sample. To get the reverse you need to reverse the parser and formatter flags so that it parses common mark but formats pegdown.

You might encounter some issues since it was not tested vigorously for that direction of conversion.
