### ISSUE TITLE
Is it possible to add class attribute to the image?

### ISSUE THREAD

**Issue by bvn13** [vsch/flexmark-java#177]
Something like
```
![alt](url){.class}
```

**Comment by vsch** [comment]
@bvn13, I have had this on the todo list for a long time. 

I was thinking of adding this extension based on kramdown implementation to the best of my ability, described here https://kramdown.gettalong.org/syntax.html#attribute-list-definitio

If you have documentation for better or more consistent implementation please give me a link. I have not proceeded with the kramdown based implementation because I am not sure it is an ideal or most intuitive syntax. 

BTW, kramdown syntax would be `![alt](url){:.class}`

**Comment by bvn13** [comment]
@vsch, sorry, I have no documentation better than you already have. I'll try to understand links and image-links parsing. If I can do this, probably I could make an extension by myself. I'll tell you.

**Comment by vsch** [comment]
@bvn13, attributes extension added to process attributes for all elements. See: [Extensions: Attributes](../../wiki/Extensions#attributes)

Maven update in progress, version 0.28.22

**Comment by vsch** [comment]
@bvn13, version 0.28.22 was a dud for attributes. I messed up the parent pom and forgot to add the new module to flexmark-all.

New build 0.28.24 has this fixed and also has a [Enumerated Reference](https://github.com/vsch/flexmark-java/wiki/Extensions#enumerated-reference)
extension  to create enumerated references for figures, tables and other markdown elements.

Repo updated. Maven update in progress.

**Comment by bvn13** [comment]
@vsch, I'll test it soon

**Comment by bvn13** [comment]
@vsch , did you push 0.28.24 into Maven repo? don't see it

**Comment by bvn13** [comment]
@vsch  , I still can't see build 0.28.24 in Maven repo. Did you push it? Only 0.28.22 is there.

**Comment by vsch** [comment]
@bvn13, maven has an indeterminate delay. It is now updated according to maven central index.
