### ISSUE TITLE
Unclosed FencedCodeBlock endOffset too small

### ISSUE THREAD

**Issue by JFormDesigner** [vsch/flexmark-java#18]
If a fenced code block is missing the closing marker, then the whole text until the end-of-file is code, but the endOffset in `FencedCodeBlock` is not at the end-of-file. It is at the end of the opening marker.

You can notice this in you fantastic [Markdown Navigator](http://vladsch.com/product/markdown-navigator) plugin when you enter `~~~` somewhere, then the text below does not get gray background (but is rendered as code in preview).

~~~java
String markdown = "~~~\ncode\ncode2\ncode3";

Parser parser = Parser.builder().build();
Node document = parser.parse(markdown);
System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
~~~
Outputs:
~~~
Document[0, 20]
  FencedCodeBlock[0, 4] open:[0, 3, "~~~"] content:[4, 20] lines[3]
~~~

BTW the AST output of `FencedCodeBlock` always outputs `lines[3]`. The number is always `3`. Should this output the number of lines in the block?

**Comment by vsch** [comment]
@JFormDesigner, thank you for the bug report and the compliment on Markdown Navigator.

BTW, are you working with the source flexmark-java or just as libraries? The reason I ask is if you are working with the modified spec format, the plugin will display the file and add some refactoring to help out. I was getting all messed up with the 3 sections: markdown, html and ast so I added rendering of these. Each is treated as injected language (at least markdown and html) so you can edit them as a fragment in a separate window.

I also added debug help for the AST, when you place the caret on one of the nodes it highlights the text corresponding to the node range in the markdown section. It isn't perfect because the IDE has trouble showing these highlights when they span the EOL, especially if the next line is blank. It is better than nothing and makes figuring out the AST range to text easier. See:

<img width="916" alt="screen shot 2016-11-20 at 7 25 10 am" src="https://cloud.githubusercontent.com/assets/10299086/20462723/cf1fe056-aef2-11e6-9eeb-b776bd6bc494.png">

<img width="907" alt="screen shot 2016-11-20 at 7 25 22 am" src="https://cloud.githubusercontent.com/assets/10299086/20462724/d1ace152-aef2-11e6-9a57-77e56558537f.png">

I can enable this feature for you on your license. You would need to remove the license and activate it again so the feature gets enabled. You will also get a few other things with it that I added for development, they won't affect anything if you don't use them.

**Comment by vsch** [comment]
@JFormDesigner, all bugs fixed. Thank you for bringing them to my attention. Some were typos in the code and working by accident. Maven has been updated.

**Comment by JFormDesigner** [comment]
Many thanks @vsch

**Comment by vsch** [comment]
@JFormDesigner, sorry it took so long. It wasn't a big job but I was committed to releasing my plugin and as it always works out just when you think you're done there is another bug. It was worth it though. Performance now is just spectacular. It is what I saw in my mind's eye when i was rewriting the parser.

Did not realize it at the time that pegdown was only half the problem. The other was JavaFX WebView. Now that both are optimized, it is a joy to use. I'm a touch typist and any delay in visual typing response and i start to slow down and make mistakes. For the past couple of month's i would turn off the preview while typing in text. Now it is smooth, the preview just stays on.

Let me know if you have any use for a Markdown plugin on IntelliJ IDEs and I'll send you a complimentary license. It will be my pleasure. If you do accept then just send me the e-mail and name for which to issue the license on my vladimir at vladsch dot com address. I'll enable the flexmark syntax and refactoring features on it at the same time.
