### ISSUE TITLE
Disable parsing of certain elements

### ISSUE THREAD

**Issue by JohannesLichtenberger** [vsch/flexmark-java#182]
Hi,

what is the best way to suppress the parsing of for instance +/- for lists, "***" for horizontal rules and so on? Do I have to write an extension for everything?

Best would be to add parser options I guess :-)

best regards
Johannes

**Comment by JohannesLichtenberger** [comment]
I think I'd need to exchange the Parsing-class. Or at least certain patterns for the pattern matching.

**Comment by vsch** [comment]
@JohannesLichtenberger, to disable parsing of whole elements there are options for all the core elements. Horizontal rule is called a Thematic Break in CommonMark and the corresponding option is `THEMATIC_BREAK_PARSER`. Set it to false in options and it will not be parsed.

For partial mods it is more difficult since the parsing options have to be provided by the individual parser.

In the case of suppressing +/- for lists, I would have to add an API to allow overriding the `Parsing` class to allow customization of parsing patterns and change all the code to use a single instance which the user can override. I will add it because not rendering the marker is not the same as not parsing the node. Since the parser will parser subsequent text as potentially part of the list item if the indentation is a match. The only robust solution is to change the Parsing patterns.

However, if you only need to modify the list item markers then an option can be added to allow you to provide the characters which mark a list, with a default of "*-+".  This will leave out the complexity of all the other part of the pattern out of the picture.

What are the other changes that you need to make?

**Comment by vsch** [comment]
@JohannesLichtenberger, for reference these are the parser flags in options to disable core block parsers:

* `Parser.BLOCK_QUOTE_PARSER`
* `Parser.FENCED_CODE_BLOCK_PARSER`
* `Parser.HEADING_PARSER`
* `Parser.HTML_BLOCK_PARSER`
* `Parser.INDENTED_CODE_BLOCK_PARSER`
* `Parser.LIST_BLOCK_PARSER`
* `Parser.THEMATIC_BREAK_PARSER`

**Comment by JohannesLichtenberger** [comment]
I think I got the rendering to work so far, just treating -/+ as normal text and rendering child nodes, as well as disabled * and ** for emphasis, only allowing underscores. However, at first the space got lost between the opening marker and the item itself in case of the lists. And I simply copied your code from the standard node renderer, but I think I didn't understand the API as of now.

**Comment by vsch** [comment]
@JohannesLichtenberger, I will add the option to specify the list item marker characters and make a release. It will give you a better solution to what you are trying to do with no code or side-effects.

**Comment by vsch** [comment]
Fix added, repo updated. Maven update in progress. Version 0.28.18

* Fix: #182, Disable parsing of certain elements, add `Parser.LISTS_ITEM_PREFIX_CHARS`, default `"*-+"` to specify which characters start a list item.

If you set this option to `"*"` then only `*` will mark a list item. Setting this to characters which may conflict with other markers is not tested for side-effects. I tried adding `/` and it works  as expected but other characters may cause issues.

**Comment by JohannesLichtenberger** [comment]
I haven't seen the regex for parsing emphasis and strong emphasis, but would it be possible to also add this? Thank you so far :-)

**Comment by JohannesLichtenberger** [comment]
Okay, I guess this is not a simple regex evaluation, as it's more complicated in CommonMark

http://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis

**Comment by vsch** [comment]
@JohannesLichtenberger, inline elements are more difficult since they are parsed by InlineParserImpl.

There are only 3 options exposed to control inline processing:

* Parser.REFERENCE_PARAGRAPH_PRE_PROCESSOR - setting to false will not process any reference definitions of the form `[...]: ...`
* Parser.ASTERISK_DELIMITER_PROCESSOR - setting to false disables `*` processing for both emphasis and strong emphasis
* Parser.UNDERSCORE_DELIMITER_PROCESSOR - setting to false disables `_` processing for both emphasis and strong emphasis

Can you please give me an idea of what customizations you want to implement so I can see how this can be done or what can be added to the API to enable you to do it easily.

**Comment by JohannesLichtenberger** [comment]
Oh, then setting Parser.ASTERISK_DELIMITER_PROCESSOR to false does the trick :-)

Thank you.
