### ISSUE TITLE
Is the library support code highlight?

### ISSUE THREAD

**Issue by zeleven** [vsch/flexmark-java#183]

**Comment by bvn13** [comment]
No, this library cannot highlight your code (jet?). But you could use something like prism.js if your app is for web.

**Comment by zeleven** [comment]
@bvn13 I mean use the library to generate proper html, and add css to highlight the code.

**Comment by bvn13** [comment]
@zeleven sure, you can use it how you just explained

**Comment by zeleven** [comment]
@bvn13 Which extension support code highlight parse? I did not find any one.

**Comment by bvn13** [comment]
oh, I misunderstood you. Did you mean the ability of this library to generaty html+css? no, it does not generate CSS. Only HTML.

**Comment by zeleven** [comment]
@bvn13 No,It doesn't need to generate html + css, just html, and I add my css for it.

**Comment by bvn13** [comment]
@zeleven you can do it using this library

**Comment by shred** [comment]
@bvn13 Can you explain a little more how I can use `prism.js` for code highlighting?

As far as I can see, a markdown code block like:

<pre>
```java
System.out.println("Hello World");
```
</pre>

is converted to:

```html
<pre class="source">System.out.println("Hello World");</pre>
```

In the generated HTML, the information that the source block was `java` is lost. How should `prism.js` know that the Java formatting style is to be applied here?

If my question is unrelated to this issue, I'm sorry. I will then open a new one.

**Comment by vsch** [comment]
@shred, the default rendering is to include the info string for the language, with "language-" as a prefix. You can see all the options for changing this in the wiki [flexmark-java Extensions](https://github.com/vsch/flexmark-java/wiki/Extensions#parser)

Your example will render as:

```html
<pre><code class="language-java">System.out.println(&quot;Hello World&quot;);
</code></pre>
```

You can change the defaults with these options:

- `FENCED_CODE_LANGUAGE_CLASS_PREFIX` default `"language-"`, prefix used for generating the `<code>` class for a fenced code block, only used if info is not empty
- `FENCED_CODE_NO_LANGUAGE_CLASS` default `""` `,<code>` class for `<code>` tag of indented code or fenced code block without info (language) specification

All you need to do is take the generated HTML and wrap it with head/body which include all the stylesheets and scripts that you need in the final page.

The library specifically does not generate these because the possibilities are limitless, as would be the support demand for these.

I use the library for my [Markdown Navigator] plugin for [IntelliJ IDEA] and other JetBrains IDEs. The plugin supports both Prism.js and HighlightJS, with the latter being quite a bit faster.

This is what I use for `Prism.js` in my plugin, the layout, default are style sheets of my plugin, the prism-default.css is stylesheet for using it with a light IDE scheme but you provide your own choice:

```html
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="layout-fx.css">
<link rel="stylesheet" href="default-fx.css">
<link rel="stylesheet" href="prism-default.css">
<title>Document Title</title>
<script src="prism.pack.js"></script>
</head>
<body>
<!-- HTML generated by flexmark-java goes here -->
</body>
</html>
```

Here is what the result are in my plugin's preview:

<img width="493" alt="screen shot 2018-02-25 at 9 41 32 am" src="https://user-images.githubusercontent.com/10299086/36642619-244e81c0-1a10-11e8-8279-f15a409ee972.png">


[IntelliJ IDEA]: http://www.jetbrains.com/idea
[Markdown Navigator]: http://vladsch.com/product/markdown-navigator
[JetBrains plugin page]: https://plugins.jetbrains.com/plugin?pr=&pluginId=7896

**Comment by AndreVanDelft** [comment]
How would you do syntax highlighting in combination with the DOCX renderer?

**Comment by lhsaq2009** [comment]
```html
<pre class="line-numbers">
    <code class="language-css">p { color: red }</code>
</pre>
```

how to add custome class for `<pre>` tag , like "line-numbers"
Is there any demo, thx.
