### ISSUE TITLE
Is there a way to include images in HTML as data: URIs? (Question)

### ISSUE THREAD

**Issue by huapeng01016** [vsch/flexmark-java#196]
Looking for something similar to --self-contained option in pandoc.

**Comment by vsch** [comment]
@huapeng01016, nothing implemented in the library but I have the code implemented in my plugin. I cannot remember if it is in the PDF converter or not.

I will add this as an option to the base html renderer. Needs modified link resolver that will return base64 encoded url for the image file.

**Comment by vsch** [comment]
@huapeng01016, if you can use Java 8, then you can make use of the following functions to encode an image into a data URI. Since the library is Java 7 compatible I cannot add this without adding dependencies or having to hack something together.

flexmark-util module has `ImageUtils` class to manipulate `Images` and `BufferedImages` so you have all the building blocks for a fast implementation.

There is also a need for you to provide resolved file path so both these steps are better done in your link resolver. All you need to do afterward resolving to a file, is provide the strings returned as the resolved URL. Like:

```
![Image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABcAAAARCAYAAAA2cze9AAABv0lEQVR42u2U2yvDYRjH3z+DwphT7AbJjRrrd0VcuDBEc7gZbiin3FKUJOUC4WY3DkWK0FpyljEitjkftvnZ+tkM25jW189v+rGcyYXy1FtP7/M8n973+z7PS/CLRv7h34K7mH3k5cpwwNz+BO5ATVEi2qZ3fBIcZ5sghGDj9Oon8GvkiAkqx7Xvwj1uz9fgNrMBev0G0gQE8qYx6HQ66LRaWK9cPHxmaQ7SNIrz07NqYXXeeY90boJcJoU/u+8XEIaWngFf+HxHAygqmSsUCIWsT4GSSDC5RfPwh5Vf1waNqgvBrF89xcrncaAgPhqRMQlY3z5EX3cLl9ert7zUPJuVpUr5uiyyVoVPXlmnBtYDNRcrn9DAaDTCZNpDeiBBafXsVzW/5vfkmUkoqZrEobqDi4WKKe9tH1dj++IbcKX2w24plko4uGV7gYutHtk/6hY3ClODEJdRj0uXC2bTPlZUhnfhuLUjQxSC2IQKGBg7HJc2rA0qMDR68nKIdocVCA8k/AM296hZ+Bbnb9JPshRnSXhdmeMRpIgi+BpBeBT6l09en1D3jRM0TeOCbcNPm8cN8xkNs4XB8zH4ux/XPdQbXCddpWkMAAAAAElFTkSuQmCC)
```

You can take a look at the code used for the `DocxConverter` link resolver for the resolution to files. [DocxLinkResolver](https://github.com/vsch/flexmark-java/blob/master/flexmark-docx-converter/src/main/java/com/vladsch/flexmark/docx/converter/internal/DocxLinkResolver.java)

Just add these to your project and you will be set.

```java
class ImageUtils {
    public static String base64Encode(BufferedImage image) {
        String imageString = null;
        ByteArrayOutputStream bos = new ByteArrayOutputStream();

        try {
            ImageIO.write(image, "PNG", bos);
            byte[] imageBytes = bos.toByteArray();

            imageString = new String(Base64.getEncoder().encode(imageBytes), "UTF-8");

            bos.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return "data:image/png;base64," + imageString;
    }

    public static String base64Encode(File file) {
        if (file == null || !file.isFile()) {
            return null;
        }

        try {
            FileInputStream fileInputStreamReader = new FileInputStream(file);
            byte[] bytes = new byte[(int) file.length()];
            if (fileInputStreamReader.read(bytes) != -1) {
                return "data:image/png;base64," + new String(Base64.getEncoder().encode(bytes), "UTF-8");
            }
            return null;
        } catch (Throwable e) {
            return null;
        }
    }
}
```

**Comment by vsch** [comment]
`ImageUtils` class is part of the `flexmark-util` module and contains the above functions.

All you have to do to encode the image is pass the image `File` to `base64Encode(File)` or pass the `BufferedImage` to `base64Encode(BufferedImage)` functions. The returned string is the URI to use for the image tag's `src` attribute.
