### ISSUE TITLE
Bold text bug

### ISSUE THREAD

**Issue by yangzhengnan** [vsch/flexmark-java#197]
** China： ** Great country on the west coast of the Pacific.
Can not display bold effect.

**Comment by vsch** [comment]
@yangzhengnan, not a bug but part of the spec. http://spec.commonmark.org/0.28/

GitHub does the same. 

Just put the bold markers around the word.

     **China:** Great Country

 **China:** Great Country

If you want leading/traling spaces then use `&nbsp;` otherwise HTML will discard them anyway

    | left margin  
      **China:** Great Country

| left margin  
   **China:** Great Country

    | left margin  
    &nbsp;&nbsp;**China:** Great Country

| left margin  
&nbsp;&nbsp;**China:** Great Country

**Comment by saket** [comment]
Hey @vsch Is it possible to customize this behavior? The spec is understandable, but when flexmark is used in a text editor, the constant switching between bold and not-bold when typing a sentence with spaces is slightly annoying as a user.
