### ISSUE TITLE
Expand issue extension to take context for dynamic urls

### ISSUE THREAD

**Issue by rnveach** [vsch/flexmark-java#206]
As GfmIssuesExtension is written now, it works great at converting issue markdown to a link, but the way it is written it is limited to only one project at a time.
Example:
https://github.com/vsch/flexmark-java/blob/07b83fb84047f7d9add8c729d1006c46517aecda/flexmark-ext-gfm-issues/src/test/java/com/vladsch/flexmark/ext/gfm/issues/ComboGfmIssuesSpecTest.java#L24-L26
The project is hardcoded to `vsch/flexmark-java`.

The only way to support multiple projects at the time is to recreate the options for each project. Besides this one extension, for me, all markdowns use the same options, so it seems a bit excess to redo all the variables each time just for this one.

Is it possible to add a new option to GfmIssuesExtension that will allows it to get the URL context from the current thread? Most web frameworks give each connection a unique thread to prevent easier coding (using ThreadLocal) and to prevent clashes. The current thread can supply the current context to flexmark to generate the URL in a safe manner and thus relieve the need to recreate the flexmark each time.
If the context isn't given, the extension can operate as it does now using the straight values given.

User Code Example:
````
private static final ThreadLocal<GfmIssuesUrlContext> URL_CONTEXT = new ThreadLocal<GfmIssuesUrlContext>();

private static final MutableDataSet MARKDOWN_OPTIONS = new MutableDataSet()
     .set(GfmIssuesExtension.GIT_HUB_ISSUES_URL_CONTEXT, URL_CONTEXT);

.....

public void execute(GfmIssuesUrlContext urlContext) {
     URL_CONTEXT.set(urlContext);

     ....
}
````

GfmIssuesUrlContext can be just a simple POJO that contains and can return gitHubIssuesUrlRoot, gitHubIssueUrlPrefix, gitHubIssueUrlSuffix.
In GfmIssuesNodeRenderer, you only have to check if the context is null or not and print the URL based on it's values or the normal option variables.

**Comment by vsch** [comment]
@rnveach, no need to modify the library to get what you want, if I understand your need correctly.

You want each thread to have customizable options so that each project running on a different thread can have a different configuration. Your need for gfm url is only a specific example and I don't see why a general problem cannot be used to address this specific one.

Just add your own extension that does this. I am including it in the next release as sample code.

I **will not be adding it to the extensions list** until I start longing to write some multi-threaded tests for the library. However, the library only has immutable statics. The rest of it operates from an instance of builder, parser or renderer. So it is thread safe as long as each thread uses its own instance or synchronizes to prevent re-entry into a shared instance.

This extension has a single thread local static which can hold any number of options. It offers a single public static method of `setThreadOptions(DataSet)` so you can have any options set per thread, with the caution that these option values have to be immutable or you need add extra code to handle their deep copy.

This applies to all options including extensions. So you can have per thread extensions.

This method, obviously has to be called from the thread whose options are to be customized.

```java
package com.vladsch.flexmark.samples;

import com.vladsch.flexmark.Extension;
import com.vladsch.flexmark.html.RendererBuilder;
import com.vladsch.flexmark.html.RendererExtension;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.options.DataSet;
import com.vladsch.flexmark.util.options.MutableDataHolder;

public class ThreadLocalOptionsExtension implements
        Parser.ParserExtension,
        RendererExtension
{
    private static final ThreadLocal<MutableDataHolder> threadOptions = new ThreadLocal<>();

    private ThreadLocalOptionsExtension() {
    }

    /**
     * Set the per thread options for flexmark-java.
     *
     * Must be called from the thread to set options to be set for
     * all flexmark-java code which uses this extension.
     * 
     * CAUTION: Do not try to make mutable data values shared.
     * setAll() copies values of keys so immutable data valued 
     * keys: Boolean, String, Integer, enums, etc., are good to go as is.
     * 
     * For mutable values you will need to add extra code to address 
     * these or you will be hunting down overwrites of data from 
     * another thread.
     *
     * @param perThreadOptions data set of the per thread options
     */
    public static void setThreadOptions(DataSet perThreadOptions) {
        threadOptions.get().setAll(perThreadOptions);
    }

    public static Extension create() {
        return new ThreadLocalOptionsExtension();
    }

    @Override
    public void extend(Parser.Builder parserBuilder) {
    }

    @Override
    public void parserOptions(final MutableDataHolder options) {
        // copy thread local options to builder
        options.setAll(threadOptions.get());
    }

    @Override
    public void rendererOptions(final MutableDataHolder options) {
        // copy thread local options to builder
        options.setAll(threadOptions.get());
    }

    @Override
    public void extend(final RendererBuilder rendererBuilder, final String rendererType) {

    }
}
```

**Comment by rnveach** [comment]
> that each project running on a different thread can have a different configuration

It is slightly different then a different project per thread.
I wanted to implement an issue structure similar to github where the issue URL is dependent on the URL the user is browsing at the time the markdown is run. So generated URL for Issue 1 can be different based on the project that is being browsed at the time.
I assume web frameworks always build a new thread and don't re-use ones that are finished. So I don't think a per thread option is any different than recreating the options every time.

> The rest of it operates from an instance of builder, parser or renderer. So it is thread safe as long as each thread uses its own instance or synchronizes to prevent re-entry into a shared instance.

By "its own instance" are you referring to the parser/renderer or something else? So once these 2 are created (by calling `Parser/Render.build()`) they are still not thread safe? So I must always recreate them anyways?

**Comment by vsch** [comment]
@rnveach, per thread options are not different than re-creating options but does let you share global static options with threads for their customization.

There are no threading issues even if you re-use the parser/renderers because once they are created they don't modify their internal state. If you do this, you will not be saving much because they are very thin wrappers around the configuration and create new instances of internal classes that do the actual parsing/rendering.

Take a look at the code in either parser or renderer (they are both structured the same way) and you will see that all of the work is done by a new instance created for the parse or render invocation.

I don't recommend that they are re-used because there is no real benefit and I don't want to deal with supporting threading issues. However, if someone knows what they are doing they can easily share the top level instances: builders, parsers, renderers and even options (as long as they do not modify mutable values, immutable values are fine).

This would only benefit in an environment where you create a lot of parsers and renderers for short jobs, can pool them to be handed out to threads as needed and returned to the pool once they are done using them. All these parser and renderer instances would have the extensions that were set during their creation. Parsing would also be done with the options used to create the parser.

The renderers are different because they get their options through the renderer builder and from the document being rendered. Options not specifically set in the **renderer's build options** come from the document node being rendered.

To change document specific rendering options (like github URL), simply set the keys for them on the document node instance before you pass it to the renderer and it will (should) work as your expect.

A `Document` node is a `MutableDataHolder` and holds all the state and options used by the parser or added by extensions during parsing.
