### ISSUE TITLE
Custom parser

### ISSUE THREAD

**Issue by shimika** [vsch/flexmark-java#210]
I want to make custom parser based on markdown syntax.

But I want to use only asterisk (*, **, ***) syntax and

Link syntax to ```[]() -> []<>```

There is so many options in parser so I can't test it all.

Is there method that turn off all of parse options?

URL Link parsing, code parsing is still doing when I set option to
```java
  static final DataHolder OPTIONS = new MutableDataSet()
      .set(Parser.ASTERISK_DELIMITER_PROCESSOR, false)
      .set(Parser.BLANK_LINES_IN_AST, true)
      .set(Parser.BLOCK_QUOTE_PARSER, false)
      .set(Parser.FENCED_CODE_BLOCK_PARSER, false)
      .set(Parser.HEADING_PARSER, false)
      .set(Parser.HTML_BLOCK_PARSER, false)
      .set(Parser.INDENTED_CODE_BLOCK_PARSER, false)
      .set(Parser.LIST_BLOCK_PARSER, false)
      .set(Parser.THEMATIC_BREAK_PARSER, false)
      .set(Parser.REFERENCE_PARAGRAPH_PRE_PROCESSOR, false)
      .set(Parser.UNDERSCORE_DELIMITER_PROCESSOR, false);
```

**Comment by vsch** [comment]
@shimika, the options you have listed are for block elements. Inline parsing is done by the InlineParser and does not have individual element options because it is all one big pile of code.

You can take a look at the InlineParserImpl and write your own and to the parser builder `customInlineParserFactory`

There are many nuances to what the code expects and if you are writing your own inline parser you will need to make it work with what the code expects. It might be easier for you just to write your own complete parser and not try to re-use pieces of the library.
