### ISSUE TITLE
HTML Deep Parser documentation?

### ISSUE THREAD

**Issue by ssikuro** [vsch/flexmark-java#215]
In https://github.com/vsch/flexmark-java/wiki/Extensions#list-parsing-options I notice there are HTML_BLOCK_DEEP_PARSER and other option names starting with that. Could you tell me what the deep parser is, how it is different from the default parser, and when it should be enabled?

**Comment by vsch** [comment]
@ssikuro, common mark has very crude HTML block handling which only uses the leading first line to determine HTML block start and a blank line for block end.

Deep HTML parsing allows more control because it parses the HTML to determine the contents and where it ends. It is one of those features that if you are not sure you need it, then you probably don't.
