### ISSUE TITLE
Add title/author for custom blockquote

### ISSUE THREAD

**Issue by firm1** [vsch/flexmark-java#219]
hello,

Thank you for your great project. I want to add feature on custom flexmark-java blockquote, but i d'ont know i can't do this.

I want to add meta informations on many blocks. My first try concern blockquote. For this mardown code : 

```
> I'll be back
source : **Arnold Schwarzenegger**
```

i want this html code : 

```html
<blockquote>
    <p>I'll be back</p>
    <p class="author"><strong>Arnold Schwarzenegger</strong></p>
</blockquote>
```

Can't you give me some advice for do this ?

I i try to parse any `source: xxx` on Parser, it hit also `source: xxx` in text without `>` blockquote marker .

Than you.

**Comment by vsch** [comment]
@firm1, one way to handle this, is as a paragraph pre-processor.

Paragraph pre-processor is invoked after the document is parsed to allow "special" processing of leading paragraph lines.

Table extension does its processing as a paragraph processor, so is the Definition extension.

All you would need to do is check if the previous sibling to the paragraph is a block quote. One thing to keep in mind for block quotes, is that they can continue to the next line as a lazy continuation even if the next line does not have the block quote marker. Check the options parser starting with BLOCK_QUOTE_.

I would recommend to either ensure that block quotes do not do lazy continuation or change your syntax to include a blank line after the block quote and the source marker line. Or alternately, allow the last line in the block quote that starts with `source:` to be used as the source line.

You can also consider other similar syntax variations:

1. As is, most complicated because of variability

       > asdfsadfsadfdsadfs
       source: author
2. Always next paragraph

       > asdfa fdlasdfjlasdfdsf
    
       source: author

3. Always last paragraph of block quote 

       > asdfa sfdasdf sa df dfsa
       > source: author
       
Option 3 is easier to manipulate because the marker node is always part of the block quote. It only needs to be split from the end of the last paragraph into its own paragraph and given an attribute. All this can be done as part of a node post processor on block quote nodes.

Option 1 without lazy continuation and option 2 always, require moving the marked text, inside the block quote and adjusting the block quote text span to include these nodes (call `node.setCharsFromContent()` on the block quote after manipulation).

You will also need to either add a custom node and your own node renderer to handle the special paragraph, or an attribute provider and return the special attribute when passed the node of paragraph with the source marker. 

All depends on what syntax options you settle on.

The most robust way, and probably the most complicated way is to disable the core block quote parser and add your own that will handle the extra line after the block quote as a special line.

General overview of parsing phases and extension writing: https://github.com/vsch/flexmark-java/wiki/Writing-Extensions
