### ISSUE TITLE
Issue with Image reference AST event order

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#22]
Hi,

I'm trying to migrate from pegdown to flexmark-java for XWiki (http://xwiki.org) and I'm hitting an issue with the order of the AST events when using the following input:

`````
![image.png][1]

[1]: image.png
``````

In pegdown the following methods were called in that order:
* visit(ReferenceNode referenceNode)
* visit(RefImageNode refImageNode)

However in flexmark-java it's the opposite:
* visit(ImageRef node)
* visit(Reference node)

The issue is that XWiki's own AST model doesn't support image reference so I was generating an image node, resolving the reference. Now it seems it's no longer possible since I only get a Reference node after method passing an ImageRef has been called.

Is there a way for me to resolve the reference inside my visit(ImageRef node)?

Thanks

**Comment by vsch** [comment]
@vmassol, in flexmark the nodes appear in the AST in the order of their appearance in the soruce document.

If you want access to the reference of the image, you don't need to visit the reference node. All referencing nodes have a method to access their reference and all documents have a property key to the reference repository that stores all references in the document, once it is parsed.

If performance is a huge concern then reference to this repository should be stored in a field of the visiting class and initialized on `Document` visit. Otherwise, just get it from the `node.getDocument()` when you need it.

```java
import com.vladsch.flexmark.ast.*;
import com.vladsch.flexmark.ast.util.ReferenceRepository;
import com.vladsch.flexmark.ast.util.TextCollectingVisitor;
import com.vladsch.flexmark.parser.Parser;

public class ImageRefVisitor {
    private final NodeVisitor myVisitor;
    private ReferenceRepository myReferenceRepository;

    public ImageRefVisitor() {
        myVisitor = new NodeVisitor(
                new VisitHandler<>(ImageRef.class, new Visitor<ImageRef>() {
                    @Override
                    public void visit(ImageRef node) {
                        ImageRefVisitor.this.visit(node);
                    }
                })
        );
    }

    private void visit(ImageRef node) {
        if (!node.isDefined()) {
            // empty ref, we treat it as plain text of its chars
        } else {
            Reference reference = node.getReferenceNode(myReferenceRepository);
            assert reference != null;

            String altText = new TextCollectingVisitor().collectAndGetText(node);
        }
    }

    void someDocumentProcessingMethod(Document node) {
        myReferenceRepository = node.get(Parser.REFERENCES);
        myVisitor.visit(node);
    }
}
```

**Comment by vsch** [comment]
@vmassol, to elaborate what I meant by get it from the document, each document is also a `MutableDataHolder()` so you can store anything in it by creating `DataKey<T>` instance of your own and calling the `MutableDataHolder.set(DataKey<T>, T)` and `MutableDataHolder.get(DataKey<T>)` to get the values. `ReferenceRepository` is just another data item in the data set.

The document data set also contains all the options passed to the parser builder, so you can create custom data keys and pass them as part of the options data set to the builder, then access them from your node visiting code to customize your visitors/renderers.

Since each node has a `Node.getDocument()` method, you can get access to the data in the document data set through the node. It does walk the AST up to the document node, hence the comment that if performance is a huge concern then it is more efficient to initialize the data you need from the `Document` node directly instead of walking the AST up to the document every time.

**Comment by vsch** [comment]
@vmassol, if you need to get offset to source position, it is available from any `BasedSequence` property of any node through the `BasedSequence.getIndexOffset(int index)` where index is the index into the `BasedSequence` implementation of `CharSequence`, valid range `[0, length()]`. 

All text data in the nodes which originates from the source of the document is represented by `BasedSequence` instances.

**Comment by vmassol** [comment]
@vsch Thanks a lot for your fast and detailed answer! I've tested it and it worked :) Thanks for the performance details too.

One small question. WDYM by the following:
>// empty ref, we treat it as plain text of its chars>

By empty ref, I guess you mean for example for this input `![image.png][]`, right? If this is the case what does "plain test of its chars" mean?

Thanks a lot

**Comment by vsch** [comment]
@vmassol, you are welcome and no to the empty ref. The empty ref I meant one that is not defined in the document.

Since the AST represents the source, and in my plugin: https://github.com/vsch/idea-multimarkdown I have completions, even for undefined refs, all elements are parsed even when they will only render their text to HTML. So if a ref image or ref link has no reference defined it will simply render the characters of the node to HTML, but in the AST it is a full fledged ref image and ref link.

The `node.isDefined()` tests for ref nodes having defined references.

**Comment by vmassol** [comment]
@vsch ok I get it.So I guess `node.isDefined()` is the same as what I was doing:

````
Reference reference = node.getReferenceNode(this.referenceRepository);
if (reference == null) {
    ....
}
````

I'll use `node.isDefined()`no, thanks.

**Comment by vsch** [comment]
@vmassol, yes it is fine and both are equivalent but isDefined() returns a member boolean without going to the trouble of getting the reference. You can use either one, whichever is more convenient in the implementation.

Unlike pegdown, you can test ref nodes for: `isDummyReference()` for having an empty `[]` following the ref node or `isReferenceTextCombined()` when there is no `[]` following the ref node in the source, with or without text in brackets.

**Comment by vsch** [comment]
@vmassol, I forgot to ask. Do you need a pegdown extension flags to flexmark-java options DataSet conversion?  There are many options in flexmark-java that need to be set to make parsing as close to pegdown's as possible, including extensions and their options. 

If you need it, I'll clean it up and make it available. I have one in my plugin I wrote for the transition from pegdown, just need to drag a comb through its hair and set it loose.

I am planning on making it available as a pegdown profile setter, any request for it will simply motivate me to get it done sooner than later.

**Comment by vsch** [comment]
@vmassol, PegdownOptionsAdapter added to the repo, will be on Maven in next release: https://github.com/vsch/flexmark-java#pegdown-migration-helper

**Comment by vmassol** [comment]
That's cool, I don't know yet if we'll use it but it's nice to have. Thanks Vladimir! :)
