### ISSUE TITLE
How to convert Headings and text into table headers and data?

### ISSUE THREAD

**Issue by tayman12** [vsch/flexmark-java#223]
I have a markdown file that looks like this

    # Title 1
    Data 1

    # Title 2
    Data 2

and I want to convert it into table such that the titles are the table's header and the data are the table's body. Could any one help?

**Comment by vsch** [comment]
@tayman12, TextCollectingVisitor removes all markdown and collects only plain text.

If you need the markdown text just use any node's getChars() method to get the markdown. If your data will not have block elements (list items, headers, etc). You will also need to convert multiple lines to a single line by changing `\n`and `\r\n`  to a space ` `.

Table cells cannot have block elements so you would need to either convert the block to some acceptable form.

DocxRenderer does not handle HTML because Docx format does not handle HTML rendering.

For DocxRenderer you need to use Markdown only. 

The double parsing should not be an issue since the parsing is very quick. 

I don't have a good idea of what you are trying to do and what your input consists of so it is difficult to come up with options.

**Comment by tayman12** [comment]
Here is what I am trying to do, I have markdown files that look like this 

    # My title
    Describe title in a paragraph
    1. element 1
    1. element 2
    1. element 3
        - sub element 1
        - sub element 2

    And some other data for the title 1
    - ***element 1 bold***: text
    - *element 2 italic*: text
    - `element 3 highlight`: text

    ## My title2
    Describe title 2 in a paragraph and there is some code
    ```
    <system.web>
    <rewrite>
       <outboundRules rewriteBeforeCache="true">
        <rule name="Remove Server header">
          <match serverVariable="RESPONSE_Server" pattern=".+" />
          <action type="Rewrite" value="" />
        </rule>
      </outboundRules>
    </rewrite>
    </system.web>
```

    ## My title 3
    Some statistical images and tables

    ![My title 3](myimage.png)

    column1|column2|column3
    :---|:---:|--:
    col1_row1|col2_row1|col3_row1
    col1_row2|col2_row2|col3_row2

I want to convert this markdown into a table in a word document such that the first column consists of the headers (here 3 headers) and the second column consists of the data corresponding to each header. Also I want the format of the text (bold, italic, table, list, .... ) to stay as it is.

**Comment by vsch** [comment]
@tayman12, the DocxRenderer cannot handle this output because markdown tables cannot contain other block elements.

DOCX can handle the format, markdown cannot.

You can re-use the current renderer to render the markdown contained between headings into a table cell. However, your document needs to start off by creating a table and rendering the whole document inside that table. 

The easiest way that I can think of doing this is to customize docx Document node rendering to extract all parts it needs from the AST, create the table and instead of the table cells telling the DocxRenderer to `docx.renderChildren()` for its content, each cell would use the rendering context to render a list of nodes for the part of the document that goes into the cell.

All the low level stuff is already there, what is missing is the ability to ask DocxRendering context to render a list of nodes. Which can be easily done by taking an arbitrary list of nodes instead of using the node's children linked list.

It is very doable but would need getting a bit into the guts of DOCX rendering, especially debugging the generated DOCX format since the current architecture never envisioned such use. Docx is a pain to work with, lots of ambiguity and Word is the worst at handling edge cases. Just complains that the document is invalid if you are missing or have included and erroneous attribute or field value.

I can see how it would be useful to rework DOCX renderer to allow this type of use case. However, I will not have time to do this for the next month or two.

**Comment by vsch** [comment]
@tayman12, I took a quick look at the DocxRenderer and it does have a CustomNodeDocxRenderer API to customize rendering. Unlike the other renderers, docx API is only used internally so I am sure it has limitation. That said, the architecture for customization is the same so a PhasedNodeDocxRenderer for Document node that uses the DocxRenderierPhase.COLLECT phase to gather the parts to be rendered, then in the DOCUMENT_FIRST part would render everything and tell the renderer to finalize everything without rendering anything else.

Right now there is no way to tell the renderer to not render anything after the node rendering is done but that should be easy to add.

**Comment by tayman12** [comment]
Can you explain more, what are the steps that I need to implement? I am not sure I understood you quite well.

**Comment by vsch** [comment]
@tayman12, to make sense of what I am talking about you need to be more familiar with DocxRendering internals. It is hard to describe the process that will make sense to someone not versed in the details of DocxRendering implementation.

Unfortunately, my time for the next while is committed to a consulting project and I will not have time to implement a sample which would demonstrate what I am describing or provide documentation for the DocxRendering extension implementation details.

**Comment by vsch** [comment]
Converting markdown to tables which contain block elements can now be done with the macros extension [Macros Extension](https://github.com/vsch/flexmark-java/wiki/Macros-Extension)

Effectively you would parse the markdown from which you would define macros for every section with a heading and use the macro expansion inline as table cell contents. Since macro sections can be any arbitrary markdown it is a simple matter of wrapping the markdown you want for the section in lines `>>>SectionName` and `<<<`. To expand the section use the `<<<SectionName>>>` macro expansion inline element.

Of course you will need to generate the section names dynamically so they are unique to the document.

The resulting markdown with macros can be converted to DOCX without the need to manipulate anything in the docx converter.
