### ISSUE TITLE
How to include WhiteSpace nodes?

### ISSUE THREAD

**Issue by ssikuro** [vsch/flexmark-java#224]
In the API doc, I see a WhiteSpace class which is a child of Node.  I'm imagining this represents a node of spaces that are not meaningful to the Markdown processing such as less-than-4 leading spaces of a paragraph such as:

````
   This paragraph is lead by ASCII spaces which don't mean any to Markdown renderer.
````

How can I make flexmark to generate these WhiteSpace nodes ? I couldn't find a configuration option.

**Comment by vsch** [comment]
@ssikuro, you cannot. Spaces are skipped by the parser.

This only needs to be done for the first line. If you take Paragraph.getChars(), this will include all the indents for the other lines.

You need to create a function includeLeadingSpacesToEOL, similar to includeToTralingEOL from #222, which will include leading spaces to previous EOL/start of document.

You may to have it do nothing if encountered non-space before previous two conditions or more sophisticated logic to prevent including spaces which the parent node considers part of its leading marker. For example block quotes treat a single space after `>` as part of their leading marker.

**Comment by ssikuro** [comment]
The way suggested in #222 doesn't quite work, unfortunately.  For example, for the quoted block like this:
```
>   Three spaces between ">" and "T" and
>     five spaces on this line.
```
The first space is part of the marker "> " and there are two spaces that are extra, from the Markdown point of view. The actual paragraph starts with "Three".  On the second line, first space after ">" is a part of the prefix, and four spaces are not considered part of the paragraph. I would like to capture those useless spaces. But the method suggested in #222 would consume all the spaces regardless of their roles. I was hoping there might be BlankLine equivalent for the spaces.

**Comment by vsch** [comment]
@ssikuro,

`Paragraph` is a `Block` is a `ContentNode`, the latter stores a list of lines belonging to the block, with the prefixes of the parents removed. I think this will give you what you are looking for.

Sorry, I forgot about that part of the AST since in my plugin, the flexmark AST is only available in the parsing process, after that it is the JetBrains OpenAPI Psi Tree.

[ContentNode.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-util/src/main/java/com/vladsch/flexmark/ast/ContentNode.java#L57-L96)

**Comment by ssikuro** [comment]
I'm not quite sure if I understand.
Do you mean pargraph.getContentLineChars(1) would return the BasedSequence representing "    five spaces on this line." (4 spaces before the 'f'), or  "five spaces on this line." (no spaces) ?

**Comment by vsch** [comment]
@ssikuro, the content lines provide the line as it was processed by the element, with all parent prefixes and indentation removed.

All elements ignore leading spaces less than code indentation level. The parser does not have this information either because these spaces are skipped and not tracked for performance and complexity reasons. It is possible to restore this information with some code. However, in 99.9% of use cases it is absolutely unnecessary.

In my plugin this is exactly what I have to do to restore the information when it is needed for JetBrains API reasons. You can use the parent node's prefix information or openMarker information but it is not homogenized because the elements have no requirement to follow a standard.

You may need to re-think how you go about restoring the document. You can take the original based sequence for the document and replace the non-white parts with your changed text. 

If you do it in reverse order from bottom to top so that offsets for your yet to be applied changes are not invalidated then you can effectively preserve all the white space without trying and without needing to keep track of changed offsets. 

If you want a general solution you can implement a way to manipulate and change the based sequence using original offsets and have them adjusted for already applied changes. The first suggestion is the simplest. Store a list of ranges you want to replace. Sort them in increasing offset order. Then step backwards through the list and apply the changes.

The result will be a changed sequence with all your replacements applied, with all whitespace and markers preserved. Just make sure you don't add any new EOLs.
