### ISSUE TITLE
Linkify geo: and xmpp: URIs automatically

### ISSUE THREAD

**Issue by contrapunctus-1** [vsch/flexmark-java#226]
It'd be helpful if Flexmark rendered geo: and xmpp: URIs as links automatically, i.e. without requiring the link syntax. Would it be possible to add this?

**Comment by vsch** [comment]
@contrapunctus-1, auto links extension uses `org.nibor.autolink` for finding links in text.

If there is an option to enable `geo:` and `xmpp:` URI recognition then it would be a matter of adding an option to have them automatically recognized. Otherwise, either a customized version of `org.nibor.autolink` or if possible an extension added to it. 

I have not looked into `org.nibor.autolink` to see if extending it is possible but suspect that it is not only possible but probably easy.

If you are so motivated you can take a look at the [AutolinkNodePostProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-autolink/src/main/java/com/vladsch/flexmark/ext/autolink/internal/AutolinkNodePostProcessor.java) which handles auto links and if `org.nibor.autolink` can be configured to recognize other resources then it would only require modifying the link extractor instance used by the node post processor to implement the functionality you want.

If you do find a solution and would like to see it as part of the library then please either PR a fix or post your changes here and I will incorporate it into the extension.
