### ISSUE TITLE
Is there any way to specify a `maxParsingTime` as in PegDownProcessor?

### ISSUE THREAD

**Issue by cng-pvl** [vsch/flexmark-java#228]
We have migrated from PegDown to flexmark, but we are missing an option to limit the execution time of the parser. 

Something like `maxParsingTimeInMillis` in `PegDownProcessor`:

```
public PegDownProcessor(long maxParsingTimeInMillis)
```

Or is there any other way to stop the parser after some time?

**Comment by vsch** [comment]
@cng-pvl, this option does not exist because the parser does not suffer from pegdown's edge case parsing going into tens of seconds or infinity. The option was added as a stop gap measure to deal with the problem. It was not a "feature".

My benchmarks for 10k+ line file of more than 500k in size, has less than 5ms parse time. 

See https://github.com/vsch/flexmark-java#benchmarks 

In the case of flexmark parser you should limit the parse time by limiting the maximum size of files that you allow to be parsed. Something on the order of 1MB for about 10-20ms parse time would be a good choice.

On average flexmark parser is 20x to 30x faster on non-edge case input than pegdown. So you should experience less resource load from the parser.

**Comment by vsch** [comment]
BTW, it was this problem with pegdown, more than any of its other shortcomings that motivated me to write its replacement for my project.

**Comment by cng-pvl** [comment]
Thank you for your very fast response!

I think we will try to limit the max file size as you suggested.
