### ISSUE TITLE
Internal API leaking

### ISSUE THREAD

**Issue by hathiphant** [vsch/flexmark-java#233]
Is it normal in method com.vladsch.flexmark.parser.delimiter.DelimiterProcessor.process(...) to have two arguments of type Delimiter and not of type DelimiterRun, given Delimiter is in an internal package and not a public package?

cf. line 54 of https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/parser/delimiter/DelimiterProcessor.java

**Comment by vsch** [comment]
@hathiphant, internal designation is very fluid since there are two types of uses: parser users and parser extenders. Many classes started off internal implementation details and wound up being exposed to allow a specific type of extension functionality.

I have not always gone and moved classes around as this occurred.

They will probably moved to non-internal, however, extensions can and do get into implementation specifics. There is no way to get around that. I would look at these as a parser user as being internal but for purposes of extensions as available.

Before the API settles down and version 1.0 is release I will have to review internal classes to see if they should be moved out of the internal package.

**Comment by vsch** [comment]
@hathiphant, I think I got all instances, also fixed for Java9+ module compatibility.

For migration notes see #283

**Comment by hathiphant** [comment]
Sorry for delay in updating my code. It seems perfect, I do not have reference to internal packages.

NB: Currently, I tested only with my current hack on Java 11 (wrapping all your jar with a custom module-info.java to build a single jmod and integrate it in a custom Java runtime).

Thank you very much for your good parser.

**Comment by vsch** [comment]
@hathiphant, no need to apologize. It is the nature of internet. It allows decoupled communications.
