### ISSUE TITLE
flexmark-ext-youtube-embedded missing test case for '@' usage.

### ISSUE THREAD

**Issue by CorneliaXaos** [vsch/flexmark-java#239]
The Youtube Embedded extension does not actually test the usage of the '@' parameter for delimiting Links.  Furthermore, because of this, Youtube Links declared this way don't actually render.

**Comment by vsch** [comment]
@CorneliaXaos, I fixed the extension. The repo is now fixed.

The extension was a contribution and I only gave it a cursory overview. Missed the fact that the renderer used `Link` instead of `YouTubeLink` which caused the `@` prefix to be ignored.

**Comment by CorneliaXaos** [comment]
Okay cool.  I was just using it as a reference while working on the extension I've mentioned before and I spotted the bug (mainly because I realized what would happen if I did something similar).  I would have fixed it myself if I wasn't trying to make my own work. :P  Thanks for getting to it so fast.

(Also, not sure if I should close this now, or wait for fix to be released..)

**Comment by vsch** [comment]
@CorneliaXaos, you can leave it open until the fix is released.

Most of the time, reporting the bug is 90% of the fix. I should examine contributed code a bit more thoroughly since I don't use them in my plugin and that eliminates a layer for catching bugs.

BTW, I just added escaping of `@` prefix so that it is possible to have a normal link prefixed with @ without making it into a `YouTubeLink`. You probably want to have this test in your code to make escaping prefixes just as expected for markdown.

**Comment by CorneliaXaos** [comment]
Will do!  I was going to eventually add DataKey options and such for customizing the prefixes, but adding escape keys will probably also be important.

**Comment by CorneliaXaos** [comment]
Hmm..  I was wondering why my escaping didn't work..  and then looked it up to see that ASCII characters aren't escaped.  I specifically decided not to use punctuation for the prefixes as I would have then directly conflicted with the Youtube Embedded Link behaviour (I would have also wanted to use '@').

So, I suppose, given that I'm using the ASCII characters as prefixes ('A', 'E', 'P', and 'V') should I bother including escape options since it would go against the usual behaviour of those characters not being escapable?  If I should, I suppose I could manually escape them by ignore the option and removing the backslashes as necessary.

**Comment by vsch** [comment]
@CorneliaXaos, it is perfectly fine to use conflicting prefixes if the two extensions are mutually exclusive or are not intended to work together. Otherwise, you will quickly run out of intuitive syntax.

Another option is to use two characters for your prefix. One being a punctuation and the second a letter: `@A`, `@E`, etc. That way escaping the `@` will allow escape of the whole prefix and disable special processing without conflicting with YouTubeLink extension.
