### ISSUE TITLE
DefinitionList extension doesn't seem to work

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#24]
Hi, I've just tried using the DefinitionExtension extension but my `visit(Definition*)` methods are not called. Looking at the sources of the extensions, it seems the code is commented out at https://github.com/vsch/flexmark-java/blob/f7025ac6bc9e5b7b9f2d3be0e641a4fd202bd58b/flexmark-ext-definition/src/main/java/com/vladsch/flexmark/ext/definition/DefinitionExtension.java#L20-L20

I need to add support for definition lists which I was handling before with pegdown (for XWiki). Any idea? 

Thanks!

**Comment by vsch** [comment]
@vmassol, definition extension is not implemented yet. It is only a place holder. I have it on a short to do list. Probably will have it in the next release that I am working on now.

**Comment by vmassol** [comment]
ok thanks again for your very prompt answer, that's really a nice support you're doing here ;)

I'll continue working on the other AST nodes in the meantime and then I'll upgrade.

**Comment by vsch** [comment]
@vmassol, support is a nice break from trying to get my dev setup working after upgrading to Sierra this morning.

**Comment by vmassol** [comment]
haha I've done the same last week (upgrading to sierra - got a new macbook pro ;)). Good luck!

**Comment by vsch** [comment]
@vmassol, I am working on implementing the Definition Lists extension. Your input would be appreciated.

I tried to see what [CommonMark Discussions](https://talk.commonmark.org/t/description-list/289) have on the subject but quickly lost interest since the discussion meanders all over the place and IMO has no bearing on the real world implementation issues because too many participants in the mix are wishful thinkers with no concern for compatibility with existing implementations and those that just love discussing how many angels can dance on a pin-head, without ever getting to working code. Neither is relevant, with the latter not realizing that the answer is simple: "depends on the pin-head trying to figure it out"

I don't want to break the blocks/inlines parsing separation and want to avoid look-ahead parsing when there are N definition term lines followed by a definition. I am going to implement the extension as a `DefinitionBlockParser` that will handle the parsing of definitions with `:` or `~` item marker,  with any markdown element content as long as it is indented using the current list item indentation rules.

A `DefinitionListBlockPreProcessor` after parsing is complete to convert a paragraph preceding a definition node to definition term lines and assemble consecutive definition terms/definitions into a single `DefinitionList`.

This has the limitation that multiple definition terms cannot be separated by blank lines. A blank line is only allowed before a definition and required between a definition and the next definition term, otherwise the next definition would be interpreted as its lazy continuation.

Here is the text for the extension overview, let me know what you think and what options do you see as desirable for the extension to have out of the box:

flexmark-java extension for definition list processing

Converts definition syntax of [Php Markdown Extra: Definition Lists](https://michelf.ca/projects/php-markdown/extra/#def-list) into `<dl><dt></dt><dd></dd></dl>` html

Converts definition lists into definition list nodes. Definition terms have an optional `:` at the end. Definition items can be preceded by `:` or `~`

Definition list is one or more definition terms with one or more definitions.

```markdown
Definition Term
: Definition of above term
: Another definition of above term
```

Definitions terms can have not definitions if they are not the last term before a definition:

```markdown
Definition Term without definition  
Definition Term  
: Definition of above term  
: Another definition of above term
```

A blank line between the definition term and definition, or the definition term and previous definition term will create a "loose" definition by wrapping its text in `<p></p>`.

```markdown
Definition Term

: Loose Definition of above term  
: Tight definition of above term

: Another loose definition term
```

Will create:

```html
<dl>
  <dt>Definition Term</dt>
  <dd><p>Loose Definition of above term</p></dd>
  <dd>Tight definition of above term</dd>
  <dd><p>Another loose definition term</p></dd>
</dl>
```

Lazy continuation of definitions is supported and definition terms which follow a definition must be separated from it by a blank line.

```markdown
Definition Term  
: Definition for Definition Term

Another Definition Term  
: Definition for Another Definition Term
```

Inline markdown is allowed in both terms and definitions. Definitions can contain any other markdown elements provided these are indented as per list indentation rules.

Multiple definition terms cannot be separated by blank lines since all but the last term(s) will be treated as paragraph text:

```markdown
Not a definition term.

Neither is this.

Definition Term
Another Definition Term

: Definition
```

**Comment by vmassol** [comment]
Thanks. Maybe this can help you: here's the test I had for pegdown implementation regarding definition lists:

https://github.com/xwiki-contrib/syntax-markdown/blob/2072a8c3ed950a10228e731c20c5ddbe18ee970c/syntax-markdown-markdown12/src/test/resources/markdown12/simple/list/definitionlist1.inout.txt

````
title1
:   definition1

    title2
    :   definition2

title3
:   definition3
`````

Notice the 3 white spaces that are ignored between the `:` and the definitions.

This was generating the following events in the XWiki model:

````
  <definitionList>
    <definitionTerm>
      <word>title1</word>
    </definitionTerm>
    <definitionDescription>
      <word>definition1</word>
      <definitionList>
        <definitionTerm>
          <word>title2</word>
        </definitionTerm>
        <definitionDescription>
          <word>definition2</word>
        </definitionDescription>
      </definitionList>
    </definitionDescription>
    <definitionTerm>
      <word>title3</word>
    </definitionTerm>
    <definitionDescription>
      <word>definition3</word>
    </definitionDescription>
  </definitionList>
`````

FYI, we also have other tests regarding definition lists but not for the MD syntax. Just mentioning them in case you find it useful. At https://github.com/xwiki/xwiki-rendering/tree/33f3ad467e3046b83bb95547a368fcb9b9aa85a3/xwiki-rendering-integration-tests/src/test/resources/simple/list you can check the `definitionlist*.test`. These tests are supported by example by the XWiki markup syntax itself.

Let me know if I can help more.

Thanks
-Vincent

**Comment by vsch** [comment]
Thanks, I can use all the test inputs I can get my hands on.

The options in definition lists are:

- `DefinitionExtension.MARKER_SPACES` default `1`, minimum number of spaces after the `:` or `~` marker for a valid definition
- `DefinitionExtension.TILDE_MARKER` default `true`, when enabled will recognize tilde `~` prefix for definition lists
- `DefinitionExtension.COLON_MARKER` default `true`, when enabled will recognize colon `:` prefix for definition lists

Options inherited from list options, not all work exactly like lists but I am trying to keep
definition lists as close a fit to list items as possible for each family. Selecting a parser
emulation profile will change the defaults for individual settings. see
[Markdown Processors Emulation](https://github.com/vsch/flexmark-java/blob/master/MarkdownProcessorsEmulation.md):

- `Parser.PARSER_EMULATION_FAMILY` default `ParserEmulationFamily.COMMONMARK`, common mark list indentation rules
- `Parser.LISTS_AUTO_LOOSE` default `true`
- `Parser.LISTS_AUTO_LOOSE_ONE_LEVEL_LISTS` default `false`
- `Parser.LISTS_LOOSE_ON_PREV_LOOSE_ITEM` default `false`
- `Parser.LISTS_LOOSE_WHEN_BLANK_FOLLOWS_ITEM_PARAGRAPH` default `false`
- `Parser.LISTS_LOOSE_WHEN_HAS_LOOSE_SUB_ITEM` default `false`
- `Parser.LISTS_LOOSE_WHEN_HAS_TRAILING_BLANK_LINE` default `true`
- `Parser.LISTS_CODE_INDENT` default `4`
- `Parser.LISTS_ITEM_INDENT` default `4`
- `Parser.LISTS_NEW_ITEM_CODE_INDENT` default `4`

**Comment by vsch** [comment]
@vmassol, definitions lists implemented in 0.9.3. Repo updated, maven central updated.

**Comment by vmassol** [comment]
@vsch Thanks a lot! You're awesome :) When we next meeting IRL I'll buy you some beers (or whatever you want!). Are you going to Devoxx France by any chance? (I live in France).

I won't have much time today to test all the nice goodies you did for me but I'll try as soon as possible + I'll reply to your mail of yesterday on the macro support too. Thanks again for all your fast answers, that's just incredible support you're doing here!

**Comment by vsch** [comment]
@vmassol, you are welcome. I live in Montreal, Quebec, Canada. I am not planning a trip to France but I look forward to meeting in person when we get the chance.

**Comment by vmassol** [comment]
ok I've tested it and there's a problem.

I'm expecting the following:

`````
  <definitionList>
    <definitionTerm>
      <word>title1</word>
    </definitionTerm>
    <definitionDescription>
      <word>definition1</word>
      <definitionList>
        <definitionTerm>
          <word>title2</word>
        </definitionTerm>
        <definitionDescription>
          <word>definition2</word>
        </definitionDescription>
      </definitionList>
    </definitionDescription>
    <definitionTerm>
      <word>title3</word>
    </definitionTerm>
    <definitionDescription>
      <word>definition3</word>
    </definitionDescription>
  </definitionList>
````

But got:

````
  <definitionList>
    <definitionTerm>
      <word>title1</word>
      <definitionDescription>
        <word>definition1</word>
        <definitionList>
          <definitionTerm>
            <word>title2</word>
            <definitionDescription>
              <word>definition2</word>
            </definitionDescription>
          </definitionTerm>
        </definitionList>
      </definitionDescription>
    </definitionTerm>
    <definitionTerm>
      <word>title3</word>
      <definitionDescription>
        <word>definition3</word>
      </definitionDescription>
    </definitionTerm>
  </definitionList>
````

Basically I'm expecting that `definitionTerm` and `definitionDescription` be sibling but your implementation puts `definitionDescription`  inside `definitionTerm`.

WDYT?

**Comment by vsch** [comment]
@vmassol, I'll fix it and make a release.

**Comment by vsch** [comment]
@vmassol, fixed and released. I also noticed that DefinitionList did not have its character span updated from contained children resulting in start, end being 0,0. 

Sorry about that. I will write it off as burning the candle at both ends for too long. Too much stuff to do and not enough time to do it.

**Comment by vmassol** [comment]
No problem, will be testing soon (finishing with adding support for wiki images now that you've implemented #29 (thanks for that!).

**Comment by vsch** [comment]
I did not connect at first your request for Wiki Images on pegdown issues but it kept nagging at me so I checked. I thought it would give you more stuff to implement and me to tick off another to do item.

I was disappointed when I found out that GitHub does not implement wiki image links. But so no point in implementing it in Pegdown.

It is a real pain to use images in GitHub wiki, without my plugin. Images have their own weird resolution rules on top of other GitHub wiki weirdness and link resolution is different for the Home page than it is for all other pages. At first I thought that I could not even use images on the home page until I figured out that it needs a wiki/ prefix on the page relative url.

Enjoy the new features.

**Comment by vmassol** [comment]
> I did not connect at first your request for Wiki Images on pegdown issues but it kept nagging at me so I checked. I thought it would give you more stuff to implement and me to tick off another to do item.

:)

This is very nice since it was a long time issue we had with pegdown!

Thanks!

**Comment by vmassol** [comment]
Definitions list working, great! :)
