### ISSUE TITLE
HtmlBlock and newline

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#26]
I have the following input:

````
hello

<table>
  <tr>
    <td>Foo</td>
  </tr>
</table>

world
````

And in the following method:

````
    public void visit(HtmlBlock node)
    {
        getListener().onRawText(String.valueOf(node.getChars()), Syntax.HTML_4_01);
    }
````

I get the following for `String.valueOf(node.getChars())`:

````
<table>\n  <tr>\n    <td>Foo</td>\n  </tr>\n</table>\n
````

I'm concerned about the last `\n`. In pegdown I wasn't getting any trailing newline, which seems better IMO since this means the newline char would be issued in another Node.

What's the rationale for including the trailing newline in the HTML node?

Thanks

**Comment by vsch** [comment]
@vmassol, in pegdown \n inclusion was an inconsistent mess across nodes. In flexmark, the \n is included  in block nodes since they start and end on full lines. The HTML block contains the \n since it is part of the text that makes up the node.

Can you give an example where this \n would make sense to make part of the next  node? You can exclude the trailing \n if you don't need it but for rendering HTML it makes sense to render with the trailing \n so hat the next element starts on a new line.

**Comment by vmassol** [comment]
> Can you give an example where this \n would make sense to make part of the next node

At some point you need to decide when the text is no longer HTML. Imagine the following input `<b>hello</b>w`. I'm sure you'd agree that `w` should not be part of the HTML node and should be part of the next node, right? For me the same could apply for `<b>hello</b>\n` (i.e. `\n` not being part of the HTML node). This seems more logical to me to not consider it to be HTML. My rationale is that you should have the smallest possible HTML content and to the maximum consider the characters to be non-HTML. Since `/n` is valid as non-HTML content, it should not be part of the HTML node IMO.

WDYT?

**Comment by vmassol** [comment]
FTM, I'll ignore the trailing new line. Thanks

**Comment by vsch** [comment]
@vmassol, \n is only part of HTML block. Inline HTML is a separate node and like any inline does not include the \n. Hence there is no need to ignore the \n in HTML blocks.

**Comment by vmassol** [comment]
>  In flexmark, the \n is included in block nodes since they start and end on full lines

In the XWiki AST model, block nodes (as opposed to inline nodes) are always separated by 2 newlines. Thus in the XWiki AST, if you have:

````
hello

<table>
  <tr>
    <td>Foo</td>
  </tr>
</table>

world
````

You'd get:

* Paragraph
  * Word ('hello')
* HTML('<table>....</table>')
* Paragraph
  * Word('world')

And if there was 3 new lines as in:

````
hello

<table>
  <tr>
    <td>Foo</td>
  </tr>
</table>


world
````

Then you'd get:

* Paragraph
  * Word ('hello')
* HTML('<table>....</table>')
* Newline (1)
* Paragraph
  * Word('world')

What's the rationale for ending all Block nodes with '/n'?

**Comment by vmassol** [comment]
I'm closing this issue since I'm now trimming the node content and it's fine with me. I'm just curious to understand the rationale. Thx.

**Comment by vmassol** [comment]
ok I guess the answer is probably that MD supports Block nodes that are not always separated by 2 new lines. Is that it?

**Comment by vsch** [comment]
@vmassol, in markdown blank lines are ignored other than to be used to mark a block end, at it is always 1 blank line that does that. Pegdown did the same. Blank lines were not part of the AST.

The AST has no blank lines, they are discarded during parsing. For my plugin I infer them from the gaps in the AST node ranges and the content of original source. Since each node has a range in original source and from each BasedSequence access to the original source through `BasedSequence.getBaseSequence()` and `BasedSequence.baseSubSequence()` methods it can be done with an AST walk or from any node by checking if previous node endOffset < this node startOffset, or this endOffset < next node's startOffset.

I never bothered to add the option of rebuilding the blank lines in the AST since it can be easily done with what is already there.

**Comment by Zhen-hao** [comment]
@vsch 
how can I get inline HTML output (without \n between blocks) from a markdown string?

**Comment by vsch** [comment]
@Zhen-hao, HTML inline does not output \n after the element. 

Can you please give me the sample of your markdown with HTML inline which causes an issue?

**Comment by Zhen-hao** [comment]
@vsch I realized that it was soft breaks that producing the newlines. problems have been solved. thanks a lot!
