### ISSUE TITLE
HTML_BLOCK_DEEP_PARSER and complex HTML/markdown

### ISSUE THREAD

**Issue by Giwi** [vsch/flexmark-java#262]
Hi, I would like to parse

```
<div>
<div>

# test 1

</div>
<div>

# test 2

</div>
</div>
```

The result is 

# test 1
`#` test 2

with HTML_BLOCK_DEEP_PARSER=true but it works fine when set to false. 
Any advice to have HTML_BLOCK_DEEP_PARSER set to true and a correct parsing?

Thanks.

**Comment by vsch** [comment]
@Giwi, actually the result is as expected without deep parser:

```html
<div>
<div>
<h1>test 1</h1>
</div>
<div>
<h1>test 2</h1>
</div>
</div>
```

<div>
<div>

# test 1

</div>
<div>

# test 2

</div>
</div>

Deep parser does not close HTML blocks until a matching closing tag is encountered. Turning on deep HTML parsing will not parse markdown headings since they are inside HTML blocks.

It results in the following HTML as expected:

```html
<div>
<div>

# test 1

</div>
<div>

# test 2

</div>
</div>
```

Rendered as:

<div>
<div>
# test 1
</div>
<div>
# test 2
</div>
</div>

<br/>

If you want markdown inside HTML blocks to be parsed then you should not turn on deep HTML parsing and use the default CommonMark parsing which ends an HTML block on a blank line. It gives more control. Deep parsing is used for better pegdown compatibility for those that need it.

**Comment by Giwi** [comment]
Ok thanks for your quick reply.

More precisely, without deep parsing, I cannot display correctly

````
<div>
    # title
   <custom-tag>
     <%
        // some text
     %>
     </custom-tag>
</div>
````

Is it possible to have both deep parsing and markdown inside HTML blocs?

**Comment by vsch** [comment]
@Giwi, there is no way to do this right now. CommonMark does not parse markdown blocks inside HTML blocks.

The only way to do this right now is to add a blank line to terminate the opening HTML block.
