### ISSUE TITLE
Option to pass sup / sub tags with FlexmarkHtmlParser

### ISSUE THREAD

**Issue by yososs** [vsch/flexmark-java#267]
HTML to Markdown conversion with FlexmarkHtmlParser
Is there an option to invalidate for each extension?

I think that it is easier to use if the following options remain as html tags.

* FlexmarkHtmlParser.SKIP_INLINE_SUP
* FlexmarkHtmlParser.SKIP_INLINE_SUB

``` java
	@Test
	public void test(){
		String html = "<html><body>"
				+ "<div>X<sup>sup</sup></div>"
				+ "</div>X<sub>sub</sub></div>"
				+ "</body></html>";
		
		final MutableDataSet parseOptions = new MutableDataSet();		
		parseOptions.set(FlexmarkHtmlParser.SKIP_INLINE_SUP, Boolean.TRUE);
		parseOptions.set(FlexmarkHtmlParser.SKIP_INLINE_SUB, Boolean.TRUE);

		String markdown = FlexmarkHtmlParser.parse(html, 20, parseOptions);
		
		System.out.println(markdown);
		Assert.assertTrue(markdown.contains("<sup>"));
		Assert.assertTrue(markdown.contains("<sub>"));
	}
```

**Comment by vsch** [comment]
@yososs, right now the skip options remove the element and only leave its inner text.

I think the skip options should be changed to an enum type with values: `CONVERT`, `SKIP`, `IGNORE` to give maximum flexibility in configuring the behaviour.

That way convert will `CONVERT` to markdown, `SKIP` will do as now and `IGNORE` will pass the HTML as is.

Original intent was to strip these out but I can see that more options make more sense.

**Comment by vsch** [comment]
@yososs, next release has added options:

0.34.28
-------

* Add: html parser options to specify how to generate some markdown formatting elements, default
  for all is `ExtensionConversion.MARKDOWN`:
  * `EXT_INLINE_STRONG` - strong 
  * `EXT_INLINE_EMPHASIS` - emphasis 
  * `EXT_INLINE_CODE` - code 
  * `EXT_INLINE_DEL` - del 
  * `EXT_INLINE_INS` - ins 
  * `EXT_INLINE_SUB` - sub 
  * `EXT_INLINE_SUP` - sup 
  
  Available settings: 
  * `ExtensionConversion.MARKDOWN` - convert to markdown
  * `ExtensionConversion.TEXT` - convert to inner text
  * `ExtensionConversion.HTML` - leave HTML as is
  
  Corresponding `SKIP_` options have been deprecated since their function is duplicated by new
  options. 

What you desire would be given by:

``` java
	@Test
	public void test(){
		String html = "<html><body>"
				+ "<div>X<sup>sup</sup></div>"
				+ "</div>X<sub>sub</sub></div>"
				+ "</body></html>";
		
		final MutableDataSet parseOptions = new MutableDataSet();		
		parseOptions.set(FlexmarkHtmlParser.EXT_INLINE_SUP, ExtensionConversion.HTML);
		parseOptions.set(FlexmarkHtmlParser.EXT_INLINE_SUB, ExtensionConversion.HTML);

		String markdown = FlexmarkHtmlParser.parse(html, 20, parseOptions);
		
		System.out.println(markdown);
		Assert.assertTrue(markdown.contains("<sup>"));
		Assert.assertTrue(markdown.contains("<sub>"));
	}
```
