### ISSUE TITLE
Table of content lower case syntax

### ISSUE THREAD

**Issue by rshah** [vsch/flexmark-java#279]
I have tried the TOC extension. it worked great. But i need the syntax in lower case of even mixed case.
So we could use `toc` or `ToC` for the syntax.

Could you advice the proper way to support this? Should i create the extension and replace the pattern?

**Comment by vsch** [comment]
@rshah, sorry I missed this one. I will add an option to make the TOC tag case insensitive. It is easier to add an option than anything else. 

Can you please share your use case that necessitates case insensitivity. I’m curious.

**Comment by rshah** [comment]
@vsch this is great,

I'm trying to display table of content(toc) from existing markdown documents using flexmark. 
But the toc's syntax used in those documents were case insensitive and i cannot change the documents. 

I just tried a quick hack by changing the toc syntax to uppercase to allow flexmark to render those documents.

**Comment by vsch** [comment]
@rshah, are there any other elments in the `[TOC]` tag? The toc extension supports options as part of the toc, https://github.com/vsch/flexmark-java/wiki/Table-of-Contents-Extension The TOC options are all lowercase

Making the TOC tag case insensitive option is easy. Making all other options case insensitive is harder because there is more code to inspect and modify.

Doing only the `[TOC]` part can be done today.

**Comment by rshah** [comment]
@vsch  only TOC tag without any options.

**Comment by vsch** [comment]
@rshah, repo updated, maven updated but may take a while to show up in maven central.

**Comment by rshah** [comment]
@vsch thank you very much for your help.

**Comment by vsch** [comment]
@rshah, you are welcome.
