### ISSUE TITLE
Table caption support?

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#28]
Hi,

I'm workjng on migrating table support in XWiki, moving from pegdown to flexmark-java. I have basic support working but advanced usages still need some tuning.

For example the following input was working before in pegdown:

````
col1   |col2    |
-------|--------|
cell11 | cell12 |
cell21 | cell22 |
[caption]
````

But with flexmark-java and the tables extension, the caption is considered as text.

I see that table caption is mentioned at https://github.com/vsch/flexmark-java/blob/7a1bc9f0727f62879dfb1f268640e52d987b33c9/flexmark-ext-tables/src/test/resources/ext_tables_ast_spec.md#L14-L14 but I couldn't find any test for it in the md file.

Could you let me know if this is implemented and if not, if it's planned?

Note that I do have a handler registered for `TableCaption` but my `visit(TableCaption node)`is not called with the input given above.

Thanks

**Comment by vsch** [comment]
@vmassol, table caption is to be implemented. I will add it. It has been on the to do list for a long time but always got bumped down because no one needed it.

**Comment by vsch** [comment]
@vmassol, table caption parsing added. Enabled by default but parsing of it can be turned off if not desired. Maven released.

**Comment by vmassol** [comment]
Awesome, tested and it worked! :)

Now the last open issue I have to be able to finish the xwiki migration from pegdown to flexmark-java is support for definitions lists :)

I'll start working on a custom extension to add support for macros, using the following syntax: http://extensions.xwiki.org/xwiki/bin/view/Extension/Markdown+Syntaxes/#HMacros. If you can think of an existing extension that is relatively similar, that would help me a lot. Thanks!

**Comment by vsch** [comment]
@vmassol, there is no single extension that handles all the variations but if I understand the syntax then I think you need to implement a `BlockParser` since the `content` part can contain anything, including blank lines.

I would recommend looking the `FencedCodeBlockParser` since it handles open/close markers and any content in between. However, your block parser will need to be a `BlockParser.isContainer()` true since it can contain arbitrary Markdown elements.

Once it detects its opening pattern and becomes active it should allow passing everything as is by returning `BlockContinue.atIndex(int)` from `BlockParser.tryContinue(ParserState)` with the index unmodified from `ParserState.getIndex()` since it will not change indents for contained blocks.

Once the closing line is detected return `BlockContinue.finished()` to absorb the line and close the block parser.

If you want to create AST nodes for the parameters then you can take a look at how `SimTocBlockParser` handles it.

The inline macros are going to be more difficult because they sort-of resemble links but don't follow the link syntax, so you can't simply let inline link parsing handle the link then look for links preceded with a `#`. Also the lopsided `{{#[macro...)` and `#[macro...)}}` will have to be handled outside of "normal" inline extensions using `ReferencePreProcessorFactory` or `DelimiterProcessor`. The former handles variations of `![]` and `[]` such as footnotes `[^]` and wiki links `[[]]` the latter will allow any type of wrapping delimiters with nesting `{}`, `{{}}` or subscript, strike, ins, etc.

You may need to put some limitations on where the elements can occur or to implement a modified version of `InlineParserImpl` and override the default inline parser through `Parser.Builder.customInlineParserFactory(InlineParserFactory)`, this will give you total control of inline parsing.

Remember, there is a limitation on what can be parsed and at what stage because the blocks are parsed first without having inline parsing. This is what gives CommonMark parsing architecture its speed.

I implemented an amalgamated parsing stage for `ParagraphPreProcessor` which has access to `InlineParser` while still in block parsing mode. These processors are used to parse out leading lines of paragraphs that are not text, like `Reference` definitions and `Tables`. These will remove leading paragraph lines that they recognize as their own, leaving the rest for other `ParagraphPreProcessor`s. What's left, if anything, will be `Paragraph` text. Paragraph pre-processing continues until no more text is removed or no text is left. So elements can be interspersed, like Table, reference definition, table, etc.

If you need inline parsing access and can limit your syntax to require it to be first line in a paragraph or to appear before any text in a paragraph, then this would be the easiest way to proceed.

**Comment by vmassol** [comment]
Thanks! I need to process this slowly now :)

BTW I was wondering whether you'd be interested in having an extension for macro support inside flexmark-java (i.e. contributing this)?

**Comment by vsch** [comment]
@vmassol, for the `{{macro}}` style syntax I can help create the macro extension for you and do initial debugging but I would like to hand it over to you since it is very specific to your project. I think that having the initial working code will make easy to follow. I would need to understand the constraints on where in text they can appear:

1. I am assuming top level file elements only,
2. no leading spaces,
3. full line content only. Meaning that the `{{macro}}` and `{{/macro}}` cannot have any characters before and the closing marker can have whitespaces trailing but not anything else.

The inline macros have an irregular syntax for CommonMark and would require either chewing up inline processing (not recommended) or I can add an API for inline processing extensions that would allow extensions to intercept processing characters outside of any inline element and "pull" text out of regular inline processing, decorate it with whatever nodes they want.

Some innards of inline processing will probably have to be exposed but such is life when you want to allow arbitrary extension functionality through the API.

For inline macros, I would add the API, framework of an extension using it and do initial debugging to validate the API, afterwards I would hand it off to you for finalization and maintenance. Again, having working code as a starting point will make the rest easy.

I have found that adding extensions to flexmark-java, start to finish with lots of tests, all passing, is faster than I could get to an initial working pegdown extension, without tests.

By the time tests are created and all passing the effort was at least an order of magnitude less. Maintaining tests was a chore too. I think once you see an extension handling your specific syntax extension you too will find it easier to work with.

What dev setup are you using?

I am using IntelliJ IDEA either Ultimate or Community Edition. It makes debugging, creating, running and updating tests a snap. I even added "combo" test output which has all test output combined to allow using the IDE diff for updating any and all parts of the test file. I also modified Markdown Navigator plugin to understand the flexmark test spec so I can format it, add options using completions and see the html expectation as both source and rendered preview. Makes working with test cases a pleasure.

**Comment by vmassol** [comment]
@vsch Thanks for the offer, much appreciated! :)

I was asking whether you'd be interested in adding support for macros as an extension in the flexmark-java project (`flexmark-ext-macros`) for 2 reasons:
* It can be interesting to others to have some kind of optional plugin system in the syntax, especially to perform dynamic things (generate a table of content, execute scripts, etc). We can choose the syntax and it doesn't need to follow the one used at http://extensions.xwiki.org/xwiki/bin/view/Extension/Markdown+Syntaxes/#HMacros
* It's an easy way to add new capabilities to the markup which is simpler than developing a flexmark extension. It doesn't match all use cases and if you wish to implement new markup elements you'd still need to write an extension but it offers an alternative which doesn't modify the MD syntax (except for the macro syntax itself ofc ;)).

I've started the work at https://github.com/xwiki-contrib/syntax-markdown/tree/95112c99eda402ee430c0f002e038035e7e817c0/syntax-markdown-markdown12/src/main/java/org/xwiki/contrib/rendering/markdown/markdown12/internal/parser/extension/macro. It's not working at this stage and is even wrong on various levels but I committed it to share with you where I am ATM.

So depending on whether you'd be interested to add some kind of macro support in flexmark-java or not, we could work together either in the git repo for flexmark-java (I'd do pull requests) or in the git repo for the xwiki markdown syntax at https://github.com/xwiki-contrib/syntax-markdown (and you could do pull requests there to help me out if that's ok with you).

Now back to the macro syntax, I don't like very much what is currently at http://extensions.xwiki.org/xwiki/bin/view/Extension/Markdown+Syntaxes/#HMacros and I'd prefer to have a single syntax for both block and inline macros. TBH I'm not sure why the person who committed that chose a different syntax and I don't think it's needed. 

If the work is to be done in the xwiki git repo, then I'd pick to use the following  syntax:

Block macros without content but with parameters:

```
paragraph1

{{macroname param1="value1" ... paramN="valueN"/}}

paragraph2
````

Block macros with content and parameter on the same line:

```
paragraph1

{{macroname param1="value1"}}content{{/macroname}}

paragraph2
````

Block macros with content on several lines (first and last newline in the macro content should be ignored):

```
paragraph1

{{macroname param1="value1"}}
content line1
content line2
{{/macroname}}

paragraph2
````

Inline macro with parameter and content:

````
Hello {{macroname param1="value1"}}content{{/macroname}} world
````

Inline macro without content and with parameter:

````
Hello {{macroname param1="value1"/}} world
````

Regarding the dev setup, I'm also using IntelliJ IDEA ;) (Ultimate edition). Been using it since 2001 AFAIR ;) I love it too.

Regarding your questions:

> I am assuming top level file elements only,

Not sure what you mean.

> no leading spaces

Sounds good. So if there are leading spaces the macro would be considered as an inline macro, as in:

````
    {{macro}}
some content
{{/macro}}    
````

> full line content only.

For block macros, yes.

Thanks!

**Comment by vmassol** [comment]
Forgot to mention that I'd be happy to maintain this macro extension, even if located in the flexmark module.

**Comment by vsch** [comment]
> I was asking whether you'd be interested in adding support for macros as an extension in the
> flexmark-java project (`flexmark-ext-macros`) for 2 reasons:
> * It can be interesting to others to have some kind of optional plugin system in the syntax,
>   especially to perform dynamic things (generate a table of content, execute scripts, etc). We
>   can choose the syntax and it doesn't need to follow the one used at
>   http://extensions.xwiki.org/xwiki/bin/view/Extension/Markdown+Syntaxes/#HMacros

I am interested in having macro capability but not sure about the syntax or options. I have to
add Jekyll macro support so the plugin can handle jekyll files properly but that syntax and
xwiki do not agree.

> * It's an easy way to add new capabilities to the markup which is simpler than developing a
>   flexmark extension. It doesn't work for all use cases and if you wish to implement new markup
>   elements you'd still need to write an extension but it offers an alternative which doesn't
>   modify the MD syntax (except for the macro syntax itself ofc ;)).

That is the other issue with adding macros, if they are not supported by the destination
processor then they are pointless unless somehow implemented in the plugin in a transparent
fashion. 

That said, the Jekyll macros will have to be added as per Jekyll syntax. I see no reason why not
have a generic macro capability extension for those that will use the library for their own
proccesisng. 

> I've started the work at
> https://github.com/xwiki-contrib/syntax-markdown/tree/95112c99eda402ee430c0f002e038035e7e817c0/syntax-markdown-markdown12/src/main/java/org/xwiki/contrib/rendering/markdown/markdown12/internal/parser/extension/macro.
> It's not working at this stage and is even wrong on various levels but I committed it to share
> with you where I am ATM.

I will take whatever I can from the code but for the extension I will create a flexmark
extension module in `flexmark-java` project using my plugin. I hacked a module copy function,
with options for various processors, nodes and options. It copies the `flexmark-ext-zzzzzz`
modules content replacing the zzzzzz placeholder with info from module creation parameters. It
is a bit of a kludge but with minimal effort and features allows me to quickly create a skeleton
of an extension, and I made it a module in the project on purpose. It compiles, builds, tests
and is subject to refactoring with the rest of the code. The latter is important since I don't
want to maintain the templates manually. 

After I create the module skeleton I will copy over the relevant code into it.

> So depending on whether you'd be interested to add some kind of macro support in flexmark-java
> or not, we could work together either in the git repo for flexmark-java (I'd do pull requests)
> or in the git repo for the xwiki markdown syntax at
> https://github.com/xwiki-contrib/syntax-markdown (and you could do pull requests there to help
> me out if that's ok with you).

If it will be offered as a macro extension then it should be kept and released with
`flexmark-java` but there is no reason why a copy with possible changes and enhancements for
xwiki cannot be kept separately. Changes can be PR'd between the two.

One reason I want to have a copy in the project is to take advantage of IDEA's refactoring
keeping all the stuff in sync. My plugin code is not in the project and every time I make API
changes I have to manually update all the dependent code in the plugin. For an extension it is
easier to let the IDEA do it.

> Now back to the macro syntax, I don't like very much what is currently at
> http://extensions.xwiki.org/xwiki/bin/view/Extension/Markdown+Syntaxes/#HMacros and I'd prefer
> to have a single syntax for both block and inline macros. TBH I'm not sure why the person who
> committed that chose a different syntax and I don't think it's needed.
 
I wasn't sure if it was your creation and was diplomatic about it. I would not adopt distinct
syntax for block or inline macros but differentiate on context like it is done for HTML blocks
and inline HTML. It makes for cleaner implementation and easier adoption.
 
> If the work is to be done in the xwiki git repo, then I'd pick to use the following syntax:
> 

I am not clear on how all these macros are used. All the macro syntax appears to be defining the
macro. Where and how do you expand the macro?

If expansion is used on the content then what syntax is used for the parameter replacement in the body
of the definition?

> Block macros without content but with parameters:
> 
> ```
> paragraph1
> 
> {{macroname param1="value1" ... paramN="valueN"/}}
> 
> paragraph2
> ```

What does a macro without content do with its parameters? Is this a definition or an expansion
of it? 

> 
> Block macros with content and parameter on the same line:
> 
> ```
> paragraph1
> 
> {{macroname param1="value1"}}content{{/macroname}}
> 
> paragraph2
> ```
> 
> Block macros with content on several lines (first and last newline in the macro content should
> be ignored):
> 
> ```
> paragraph1
> 
> {{macroname param1="value1"}}
> content line1
> content line2
> {{/macroname}}
> 
> paragraph2
> ```
> 
> Inline macro with parameter and content:
> 
> ````
> Hello {{macroname param1="value1"}}content{{/macroname}} world
> ````
> 
> Inline macro without content and with parameter:
> 
> ````
> Hello {{macroname param1="value1"/}} world
> ````
 
I am fine with the syntax as long as there is no kludged syntax for inline processing. I don't
see why there should be a distinction. I would even allow up to 3 spaces or whatever the
processor family treats as non-indenting spaces. This way the macros are indistinguishable from
markdown text that they replace.

I need to understand how they are defined, used and what is the resulting output of their
expansion. 

- What are parameters used for? 
- Are they replaced in the content?
- If they are, do they use `{paramName}` syntax? Other syntax?
- Macro's should not be nested. Too difficult on the non-recursive parser but can be done 
- Is there a way to include a file that defines macros or do they need to be defined where used?
 
In the extension would add options:
 
- for the wrapping characters both open and close, so the same extension can be used with `<?`
  and `?>` to simulate PHP or anything else.
- to have or not have the `/macroname` being the close tag or use another block
  closing marker.
- for inline opening/closing sequence for the same reason `<?=` and `?>` could be used for
  example. 
 
> Regarding the dev setup, I'm also using IntelliJ IDEA ;) (Ultimate edition). Been using it since
> 2001 AFAIR ;) I love it too.
 
I wish I had started using it back then, I could have benefited from it. 

If you are not using Markdown Navigator you will probably want to start. Send me by e-mail, your
e-mail address and name you want on the license and I will issue one for you and add the
flexmark-java test spec support. You will be able to work with test specs comfortably.
Navigation, refactoring, completion on options and automatic language injection for Markdown
source part of the spec and HTML for expected HTML part of the spec. Additionally, when the
caret is on a node in the AST part of the spec, will highlight the corresponding text in the
source part. Makes it easier to check offset alignment between source and AST.
 
> Regarding your questions:
> 
> > I am assuming top level file elements only,

Once I understand what macros do I would be able to argue for non-file elements. Definition
would definitely be limited to file level. Expansion would have to be anywhere except in
indented code, fenced code and inline code.

> 
> Not sure what you mean.
> 
> > no leading spaces

Some markdown elements in some processors that are parsed as blocks only do so if the element
does not have any leading spaces. One processor does not allow leading spaces before `#` for ATX
headings. So a space will make the processor treat it as just another `#` and not ATX heading marker.

> Sounds good. So if there are leading spaces the macro would be considered as an inline macro, as
> in:
> 
> ````
>     {{macro}}
> some content
> {{/macro}}    
> ````

I would not use leading spaces for this since it will conflict with indented code. 

I don't see why block macros, that don't contain any block elements cannot be used as inline
macros without needing any distinction in the syntax. Again, if I understood their use cases it
would make it easier to bring up relevant points and alternatives.

> 
> > full line content only.
> 
> For block macros, yes.
> 
> Thanks!
>

**Comment by vmassol** [comment]
Continuing discussion on #33

**Comment by vmassol** [comment]
Closing since Table caption has already been implemented.
