### ISSUE TITLE
BlankLine nodes within BlockQuote change in behaviour

### ISSUE THREAD

**Issue by spand** [vsch/flexmark-java#294]
Previously in `0.19.3` the following markdown produced two `Paragraph` nodes as children of a single `BlockQuote`:
```
> Paragraph1
>
> Paragraph2
```

After updating to `0.40.0` it now gives the following with a `BlankLine`:
```
Document[0, 29]
  BlockQuote[1, 29]
    Paragraph[3, 14]
      Text[3, 13]
    BlankLine[14, 16]
    Paragraph[18, 29]
      Text[18, 28]
```

Reading #225 it I get the gist that this might not be intended behavior unless `Parser.BLANK_LINES_IN_AST` is `true`. Is it ?

Looking through the changelog doesnt reveal anything to me either.

**Comment by vsch** [comment]
@spand, I was too lazy to add code to delete blank line nodes for Block Quotes and Aside nodes after fixing blank line handling for these nodes in 0.35.2

These need to be inserted into the AST during parsing to extend the block character span to include trailing blank lines otherwise:

```markdown
>
>
>
```

Results in the Block Quote AST node only containing the first `>` marker when it should contain all characters all the way to the EOL of the last line of the block quote.

I added code to remove BlankLine nodes (unless BLANK_LINES_IN_AST is enabled) after the block is closed and the spanning characters are computed.

Will release update in 0.40.2

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
