### ISSUE TITLE
Add ability to pass parameters to wiki links and wiki images

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#30]
Use case 1: be able to support query string and anchors. Note that the reason for not use `reference?a=b&c=d` is to be able to easily support having `?`in wiki page names.

Use case 2: be able to resize the images.

Syntax proposal: `[[label|reference||parameters]]``

Examples:
* `[[label|reference||queryString="a='b'&c=d" anchor="anchor"]]`
* `[[image||width="300px"]]`

Alternative: something like: `[[label|reference]](parameters)`.

Yet another alternative is to make it even more generic and be able to pass parameters to any inline or block syntax element (as it's possible in the xwiki syntax for example). In the xwiki syntax you write the following:

`(% a="b" c=d %)<element here>`

Example1: `(% a="b" c=d %)[[reference]]`
Example2: Parameter for a list (e.g if you wish to pass the type of list):

````
(% style="list-style-type:disc" %)
* item 1
* item 2
````

Then it's up to the renderer to decide what it'll do with the parameters and what it'll honor.

The last alternative is to do nothing and force the user to use HTML but it's not very nice and I've already had users asking for support for wiki link anchors.

Let me know what you think. I could simply start by implementing support for `reference?a=b&c=d` for now and provide an escape character when users want to use `?`in the wiki page name (or have them URL-encode it).

Thanks

**Comment by vsch** [comment]
@vmassol, your request triggered some inspection of the code to see how best this should be handled and resulted in some API and implementation changes related to `WikiLinks`.

In general I am all for implementing syntax extensions that are already used by popular Markdown processors. I am not so keen on implementing extensions that are incompatible with any processor unless they are generally useful and the syntax extension fits withing Markdown or CommonMark philosophy.

It is too easy to start adding all kinds of extensions that create a kaleidoscope of variety but not a consistent mosaic picture.

1. adding extra pipes to the wiki links makes it not standard with any processor and in my opinion looks a bit like a kludge.

   However, if this is the syntax that suits your application best then it should be handled outside the parser/renderer by implementing a `LinkResolver` that handles the extra parameters since the whole string for the link part of the wiki is now passed to it for processing.

   It will eliminate the need to change the `WikiLinkRefProcessor` and `WikiNodeRenderers`, it is also something every use of flexmark-java probably needs to implement anyway to make sure that wiki link resolution logic is applied.

   You can take a look at the `WikiLinkLinkResolver` and just implement a modified version and register it in your extension. I do that for my plugin to apply GitHub wiki and regular resolution logic.

   The same link resolver can handle image parameters but it will need to do so in conjunction with an `AttributeProvider`, data between the two can be shared through a DataKey in the options holding a repository of node to attributes. The reason you need to share data is that the link is first resolved then attributes are requested for it. So you will need to store the attributes in a `HashMap` indexed by the node, in the `LinkResolver` so that you can retrieve them in the `AttributeProvider` for the link.

   You can use the `Attributes` and `Attribute` classes which I enhanced to allow special handling for `class` type and `style` so that class attribute will use space separated list of class names and style uses a semi-colon separated list of `name=value` that way style intelligently replaces exiting values instead of always appending.

2. I am leaning toward Kramdown attribute syntax using `{ }` post-fix notation. It is already popular with many processors and I need one implemented for Jekyll support.

   I will be adding an API to allow custom inline processing beyond the `LinkRefProcessor` and `DelimiterProcessor` to handle non-nested inline processing such as `(%` and `%)` so that you can implement any form of inline attribute processing required.

3. WikiLink extension has some changes if you are are processing link refs, text or the node's child nodes or want to implement handling of `||` processing in the link

   - Previously wiki link nodes ignored any inline delimiter processing and used the text as is. The node also included all the text in the wiki link as its child text node.

     In the next release there is a new option `WikiLinkExtension.ALLOW_INLINES` for allowing inline processing in wiki link text portion and is `false` by default. Only inlines in the text part when using `|`, or all of it if text and link are combined, are processed. Only the text portion with any inlines is included as children of the wiki link and wiki image nodes. The link portion is accessible through the `WikiNode.getLink()` method on both wiki node types.

   - Text from link was split on the first `|`, this is now dependent on the `WikiLinkExtension.LINK_FIRST_SYNTAX` setting. If links are first then the last `|` will be used to split the text from the link. This way you always have the `||` in the link part.

   - Now wiki links pass the full link text for link resolution, previously only the `pageRef()` portion, which was before the first `#` and the anchor ref was appended to the resolved link. Now that is the responsibility of the link resolver. It allows more flexible processing, including adding parameters in the link portion.

I will be making the next release today with the changes and bug fixes to wiki extension.

**Comment by vmassol** [comment]
> It is too easy to start adding all kinds of extensions that create a kaleidoscope of variety but not a consistent mosaic picture.

I completely agree!

Thanks for this detailed answer. At this stage I don't fully understand why implementing my own version of `WikiLinkLinkResolver` and registering it (not sure how to do that actually) would be better than implementing my own link reference parser in my `visit(WikiLink node)` method. I see that `node.getLink()` or `node.getPageRef()` both return the full reference so if I have as input `[[label|reference|params]]`, I get `reference|params`, which I could then parse myself to separate the reference from the parameters. And this is fine with me BTW.

Thanks

**Comment by vsch** [comment]
@vmassol, the reason I recommended a link resolver over implementing a new node parser and new node is to eliminate duplication and you will need to implement you own link resolver if you create a modified copy of the wiki extension. The `WikiLinkLinkResolver` is specific to wiki extension nodes. 

Registering all extension points is the same. For a parser extensions it is done in `ParserExtension.extend(Builder)` by calling one of the custom registry on the builder parameter:
 
- `Parser.Builder.customBlockParserFactory(CustomBlockParserFactory)`
- `Parser.Builder.customDelimiterProcessor(DelimiterProcessor)`
- `Parser.Builder.customInlineParserFactory(InlineParserFactory)`

For a renderer extensions it is done in `HtmlRendererExtension.extend(Builder)` by calling one of the custom registry on the builder parameter:
 
- `HtmlRenderer.Builder.attributeProviderFactory(AttributeProviderFactory)`
- `HtmlRenderer.Builder.htmlIdGeneratorFactory(HeaderIdGeneratorFactory)`
- `HtmlRenderer.Builder.linkResolverFactory(LinkResolverFactory)`
- `HtmlRenderer.Builder.nodeRendererFactory(NodeRendererFactory)`

Note on getting the link from `WikiNode.getLink()` or `WikiNode.getPageRef()`. The former returns the whole link text, the latter only the portion before the `#` anchor ref, if one was part of the link text.

If you are going to generate errors or not parse a wiki link if its parameters are "wrong", which you cannot do in a link resolver, then you are propabably better off implementing your own wiki link parser, node renderer and link resolver, which you will need to do anyway for your own wiki node.

That is the reason I recommended just adding a link resolver to override the default one provided by the extension. Your own wiki nodes will need to implement it anyway. Either way, you have many hook points and options for extending the core and extensions.

**Comment by vmassol** [comment]
ok thanks for the explanations.

Right now I already have a Markdown Renderer in XWiki (takes an XDOM object as input - this is the XWiki AST) and generate any output syntax from it (including Markdown, which is needed for our WYSIWYG - We convert from MD to HTML, then the users edits in WYSIWYG and then from HTML to Markdown). So I don't need to integrate that with flexmark-java.

So I'll use my own parser ATM (especially since I already have various bits for it).

One question though: Do you have an escape character for `|`for wiki link syntax.

Imagine that I want the link label to be `hello|`, how do I do that?

**Comment by vsch** [comment]
@vmassol, I'll add the logic for the escape in parsing for `|`. Right now it is done in the node without checking for `\` before. I will also add an option to allow escapes in wiki links. Some processors treat all characters other than `#` as part of the page ref and no escapes allowed, GitHub for example.

**Comment by vsch** [comment]
@vmassol, added to the repo, I will do a full release tomorrow after validating the changes through my plugin.

**Comment by vmassol** [comment]
Thanks

**Comment by vsch** [comment]
@vmassol, update 0.10.3 released. maven updated.

**Comment by vmassol** [comment]
@vsch Actually I had tested it when you pushed the change back then and it's working fine, thanks!

**Comment by vmassol** [comment]
Closing since I'll handle this by parsing the link reference on my side.
