### ISSUE TITLE
parser option for image paths

### ISSUE THREAD

**Issue by schiessle** [vsch/flexmark-java#308]
Some markdown editors use a slightly different paths for images (and probably other content). E.g. QOwnNotes adds the prefix 'file://' for every path to an image. In order to make Markor compatible with it, it would be great if you would support a config option for such prefixes, see https://github.com/gsantner/markor/issues/463 This would enable compatibility with Nextcloud Notes and one of the most used desktop client for it. Thanks for considering this feature request!

**Comment by vsch** [comment]
@schiessle, the mapping of links to resolved links is done by the link resolver. DocxConverter has one implemented that will map a link based on defined page URL and site URL to resolve page relative link addresses and site relative (ones staring with `/`).

You can implement a custom link resolver that will handle any requirements with a few lines of code. I deliberately left this out because link resolution is highly implementation specific.

I provided the DocxLink Resolver as a sample which can be used as is or customized.

[CustomLinkResolverSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/CustomLinkResolverSample.java)

**Comment by rosscallister-rit** [comment]
> @schiessle, the mapping of links to resolved links is done by the link resolver. DocxConverter has one implemented that will map a link based on defined page URL and site URL to resolve page relative link addresses and site relative (ones staring with `/`).
> 
> You can implement a custom link resolver that will handle any requirements with a few lines of code. I deliberately left this out because link resolution is highly implementation specific.
> 
> I provided the DocxLink Resolver as a sample which can be used as is or customized.
> 
> [CustomLinkResolverSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/CustomLinkResolverSample.java)

broken link: now https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/CustomLinkResolverSample.java

**Comment by vsch** [comment]
@rosscallister-rit, thanks. Fixed.

There will be a lot of these as the library is refactored for 0.60. I did not find any tools to help identify broken links in github comments. I might have to throw something together, just have to find the time.
