### ISSUE TITLE
Simple Block with triple backtick (```)

### ISSUE THREAD

**Issue by gautamr** [vsch/flexmark-java#343]
**question:** Can we render MD -> HTML `<pre>test<\pre>` with triple backtick (```) like Slack?

When I use single backtick (\`) or triple backtick (```) I'm getting same HTML, but is it possible to get `<pre><code>test</code></pre>` in case of triple backtick 

I am getting
``` 
"`test`" => "<p><code>test</code></p>\n"
"```test```" => "<p><code>test</code></p>\n"
``` 

I want
```
"`test`" => "<p><code>test</code></p>\n"
"```test```" => "<p><pre><code>test</code></pre></p>\n"
or
"```test```" => "<p><pre>test</pre></p>\n"
```

**Comment by vsch** [comment]
@gautamr, what you want can only be done with a custom node renderer for inline code block because it is not standard CommonMark or Markdown rendering.

I added a sample to do exactly what you described in [InlineCodeCustomRenderingSample.java]

Input:

``````markdown
`test`

``test``

```test```

````test````

``````

Rendered result:

``````html
<p><code>test</code></p>
<p><code>test</code></p>
<p><pre>test</pre></p>
<p><code>test</code></p>

``````

[InlineCodeCustomRenderingSample.java]: https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/InlineCodeCustomRenderingSample.java

**Comment by gautamr** [comment]
@vsch Thank you so much! It's so kind of you for the example you have written. It is working just as I expected :) . I wish I could contribute to this library.

**Comment by vsch** [comment]
@gautamr, you are welcome.

All contributions are welcome, especially now that the popularity and library size has grown to where it takes significant effort on my part to keep up.

I would recommend starting with the architecture overview https://github.com/vsch/flexmark-java/wiki/Writing-Extensions go get a rough idea of how it all hangs together. After that reading and working with code to get a detailed understanding of the code.

**Comment by gautamr** [comment]
@vsch cool, I'm adding this reading to my TODO list! Closing this question. Thank you again :)
