### ISSUE TITLE
Problem with escapes in links

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#35]
I have as input: `[link](\(foo\))` (see http://spec.commonmark.org/0.27/#example-464).

In my `visit(Link node)` the reference text I get is `\(foo\)`which means that the escapes are not processed. Thus when I render this in HTML I get: `<a href="\(foo\)">...` instead of `<a href="(foo)">...`.

Would be nice if flexmark-java could process the escapes and have a way in a `Link` object to get the processed reference.

WDYT?

**Comment by vsch** [comment]
@vmassol, it is a bug, same as was in wiki links. It is a left over from changing from escape processing during parsing in commonmark-java to source based AST which keeps escapes as is to have source matching. I'll fix it and make a release with the accumulated fixes.

**Comment by vmassol** [comment]
ok great, thanks!

**Comment by vsch** [comment]
@vmassol, just checked and the rendering of link does do escape correctly. So what you are referring to is links in the AST. Which is correct since the AST has source based text which includes all escapes.

What you need to do to get unescaped content is to apply the `unescape()` method on the `BasedSequence`.

All the text in the AST is source based so you can get the offset into original source via:

- `BasedSequence.getStartOffset()`
- `BasedSequence.getEndOffset()`
- `BasedSequence.getSourceRange()`
- `BasedSequence.getIndexOffset(int)`

This means that the string represents sub-sequence of the original source.

**Comment by vmassol** [comment]
hmmm ok will test. So I guess it means that all places where I call `node.getText()`, `node.getUrl(), etc I need to also call `unescape` as in `node.getText().unescape()`.

**Comment by vmassol** [comment]
Ok just tested and it works.

BTW other question: is there some escape utility class that I can reuse in my Renderer to escape characters depending on the context (whether I'm in a link reference, link label, etc)?

Thanks

**Comment by vsch** [comment]
@vmassol, take a look at [CoreNodeRenderer](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java) for all the unescaping that it does before rendering and the [Escaping](https://github.com/vsch/flexmark-java/blob/master/flexmark-util/src/main/java/com/vladsch/flexmark/util/html/Escaping.java) class used for all kinds of input conditioning such as normalizing EOL, unescaping, escaping, url encoding and decoding.

The best examples or usage are in the core code and in the extensions.

**Comment by vmassol** [comment]
Closing since it's woking fine.
