### ISSUE TITLE
(Identity) Markdown Renderer

### ISSUE THREAD

**Issue by juanmirocks** [vsch/flexmark-java#359]
## Use case / problem

In my parsing of markdown, I add some own post processors to, for example, remove inline images and displaying them back to what they were as text (`![alt](url)`). This is analogous to the sample code in [TokenReplacingPostProcessorSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/TokenReplacingPostProcessorSample.java).

This is simple enough to do. However, I'm wondering, whether there is a flexmark-java native way to actually render parsed `Node`s back to their Markdown form. For more complex cases, like dropping or adding extra elements at will (e.g. as markdown sanitizers or prohibiting "illegal" elements) the need to render back to Markdow makes sense to me.

The desired functionality even makes possible to test that indeed the markdown parser is actually able to reproduce the same parsed text. Analogous as an identity function.

## Describe the solution you'd like 
A "MarkdownRenderer" to render a markdown-parsed AST back into a markdown string, including being able to render any subnode. Of course, it should also be possible to render any AST built programmatically.

## Describe alternatives you've considered
My own addhoc `Node` `toString` functions.

## Additional context
My bad if this functionality already exists, but I did not find it in the code or documentation.

**Comment by vsch** [comment]
@juanmirocks, no need to apologize for not knowing all the functionality that already exists. I have on occasion started adding a feature only to discover that it is already implemented in the code.

What you want is the Formatter renderer which renders the AST as markdown. There are caveats for creating new nodes or changing their text since each node's text is expected to come from a single chunk of text for offset purposes. This causes some overhead since you cannot just use a string and must use `PrefixedSubSequence` to add string prefixes and provide an offset in the original text where this prefix is inserted.

In some cases the formatter can make over-simplified assumptions about the text/offsets so it may produce erroneous output for modified AST. If you find any such cases please let me know so I can fix them quickly.

You can take a look at the two samples which modify the AST and render the modified markdown:

[FormatterWithMods.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/FormatterWithMods.java)  
[FormatterWithMods2.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/FormatterWithMods2.java)

**Comment by juanmirocks** [comment]
Thank you @vsch ! This is a good start and I will investigate. Closing for now.
