### ISSUE TITLE
Create extension to replace heading AST nodes

### ISSUE THREAD

**Issue by alexmgarcia** [vsch/flexmark-java#369]
Hello, I would like to create an extension to replace `Heading` AST nodes and its children by other nodes. I am not sure if what I really need is to avoid using the `HeadingParser` and use a custom parcer to do that by generating a new block.
Basically what I need is, supposing that I have the document:
```
# Title
key1: value
key2: value2
## Sub-Title 1
key3: value
Content text of the sub title 1 section
## Sub-Title 2
key3: value
Content text of the sub title 2 section
```

Then instead of having multiple `Heading` blocks, I need to have a `CustomBlock` for the `Title` section with metadata including key1, key2 and into its children to have two instances of `ChildCustomBlock` (for Sub-Title 1 and Sub-Title 2 sections) with metadata including key3 and in each of those instances to have the remaining blocks that are already created by flexmark (e.g. `Paragraph`, `Image`, `BulletList` and so on)

I was thinking in extending the `Block` class with `CustomBlock` and to extend `Block` class with `ChildCustomBlock`
Then I was thinking in creating two parsers: one for the `CustomBlock` and another for `ChildCustomBlock` (both parsers having the `HeadingParser` removed from its `getBeforeDependents` method) but I am not sure if this is the best way to do it according to the defined architecture of flexmark.

Is there a sample that I can base on to accomplish what I described?

**Comment by vsch** [comment]
@alexmgarcia, you should be able to get by with only a `DocumentPostProcessor` which will remove heading blocks and replace them with your own custom blocks. Effectively, rearranging the whole AST since headings are not hierarchical and your blocks are.

You will also need to parse leading lines of paragraph text for `key: value` syntax. You can do this via `ParagraphPreProcessor`, that way these elements will not be misinterpreted as inline elements and remaining text will be properly parsed for inline markup.

Since you are not adding any text in your customizations then it would be straight forward to re-arrange the AST for custom hierarchy.

I am assuming that the testing of headings includes all heading levels. So that H3 will be included as a custom sub-block in H2.

Extension which uses `NodePostProcessor` extensively is [`flexmark-ext-definition`](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-definition) module. It has a mix of parser extensions with node post-processor to arrange definitions and terms into a definition list.

`DocumentPostProcessor` is similar to `NodePostProcessor` and used in [AnchorLinkPostProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-anchorlink/src/main/java/com/vladsch/flexmark/ext/anchorlink/internal/AnchorLinkPostProcessor.java) In some cases it is easier to handle the whole document and handle determining what you process in your own code. In your case it is will probably be easier to work on the document instead of just heading nodes but either one will work.

Extensions which implement a `ParagraphPreProcessor` are:
* [EnumeratedReferenceParagraphPreProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-enumerated-reference/src/main/java/com/vladsch/flexmark/ext/enumerated/reference/internal/EnumeratedReferenceParagraphPreProcessor.java)
* [TableParagraphPreProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-tables/src/main/java/com/vladsch/flexmark/ext/tables/internal/TableParagraphPreProcessor.java)

[Writing Extensions](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions) gives an overview of various extension points.

**Comment by alexmgarcia** [comment]
Your explanation solved my issue. Thank you!
As soon as I have a correctly working Extension I will do a pull request to flexmark 👍
