### ISSUE TITLE
Markdown Validation

### ISSUE THREAD

**Issue by realdadfish** [vsch/flexmark-java#395]
I'm trying to integrate some basic markdown parsing / validation in my build process which is used to validate a hand-written CHANGELOG.md file. From time to time I see colleagues make small mistakes where I wish I'd have a tool that would automatically flag these issues and break my build, things like invalid links (`Foo(https://...)` instead of (`[Foo](https://...)`), missing whitespace (`-something` instead of `- something`), stuff like that.

Is there any kind of "strict" option in the parser that I missed where the parser would bail out on inconsistencies / issues like this? If not, would it be feasible to implement such a thing or is the markdown spec too loose for any validation check?

**Comment by vsch** [comment]
@realdadfish, unfortunately Markdown does not have syntax errors and all text results in valid parsing.

You can add lint type checker for Markdown by adding rules based on issues you find in the CHANGELOG.md file. Over time your rules will grow and eventually cover most issues you encounter.

**Comment by realdadfish** [comment]
Yes, I already do basic regex-based checking of the file, but this has obviously it's limits. I was wondering if I could eventually use / develop some plugin that would would work on the parsed AST from flexmark-java in which I could encode the needed rules. Would this be possible, if so, what would be a good starting point?

**Comment by vsch** [comment]
@realdadfish, I think a rule based visitor would be the simplest and most flexible.

Each rule would have a list of node types to which it should be applied and a regex. As an option some rules could be node specific to allow checking individual parts of a node, such as info string or content of fenced code, for example, or link text, and link address.

The main loop would be a visitor with only a generic `Node` visit method, which would use the node class to get the applicable rules and apply them to the node or its parts.

This way the regex will be simplified since it is only applied to a node, or part of a node, not the whole file.

**Comment by vsch** [comment]
@realdadfish, as a future implementation you can make the rules extensible so that a `RegEx` based validator is available and applied to `Node` via `Node.getChars()`, other node specific validators can be `RegEx` based or code based for maximum flexibility and would specify node classes to which they apply.

Then the configuration would consist of configuring a list of rules and visiting the document.

**Comment by realdadfish** [comment]
OK, thanks for the pointers, I'll see with what I can come up with. Will close this for now. Thanks again!
