### ISSUE TITLE
Enabled inline types

### ISSUE THREAD

**Issue by fynnfeldpausch** [vsch/flexmark-java#410]
**Is your feature request related to a problem? Please describe.**
I am trying to parse Markdown but disable the link functionality. A text like "`*Hello World* [Foo Bar](https://www.google.com)`" should be rendered as "`<em>Hello World</em> [Foo Bar](https://www.google.com)`".

**Describe the solution you'd like**
A new option should be added to the parser to easily disable link and image processing.

**Describe alternatives you've considered**
I am currently trying to write a custom parser and am struggling to come up with a solution.

**Comment by fynnfeldpausch** [comment]
Found it in the docs, sry.

**Comment by fynnfeldpausch** [comment]
While I found a lot of possible configurations, I did not find any option to disable the processing of links & images. Can someone point me in the right direction?

**Comment by vsch** [comment]
@fynnfeldpausch, the easiest way I can see of implementing what you want is to create a custom node renderer for `Link` and `Image` nodes which would just render the node text instead of link/image HTML.

It is much easier than trying to not parse the links because the logic for these inline elements is intertwined with a lot of other inline elements, including refrence links and images.

You can take a look at custom node renderer samples as a starting point:

[NodeRendererSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/NodeRendererSample.java)
[NodeRendererSample2.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/NodeRendererSample2.java)

**Comment by fynnfeldpausch** [comment]
Works like a charm. Thanks for the hint!
