### ISSUE TITLE
flexmark-profile-pegdown maven

### ISSUE THREAD

**Issue by zhanjiejun** [vsch/flexmark-java#44]
Where can I get the jar **flexmark-profile-pegdown**?
I couldn't find it in any maven repository.

**Comment by vsch** [comment]
@zhanjiejun, sorry about that. I keep messing up the module name and it does not deploy but without errors. I think it is now fixed. I checked manually the content for flexmark-profile-pegdown before releasing the staged repo this time.

Maven released, it may take a bit before the index is updated. 

If you don't absolutely need the jar and can use the source file then grab the source for this file from this repo: https://github.com/vsch/flexmark-java/blob/master/flexmark-profile-pegdown/src/main/java/com/vladsch/flexmark/profiles/pegdown/PegdownOptionsAdapter.java, 

it is a single file that you may want to customize instead of using it as is.

**Comment by vsch** [comment]
@zhanjiejun, maven index updated.
