### ISSUE TITLE
kramdown definition lists

### ISSUE THREAD

**Issue by mnlipp** [vsch/flexmark-java#58]
Kramdown supports definition lists (https://kramdown.gettalong.org/syntax.html#definition-lists). Setting the KRAMDOWN profile in flexmark does, however, not enable this feature.

**Comment by vsch** [comment]
@mnlipp, selecting KRAMDOWN defines the list processing to match Kramdown for extensions you should add these to your options with the Parser.EXTENSIONS key.

I updated the basic usage sample to include the extra extension that are part of kramdown.

Please note that the table extension matches Php Extras and does not include table footers or table separators using + symbols.

```java
    void kramdown() {
        MutableDataSet options = new MutableDataSet();
        options.setFrom(ParserEmulationProfile.KRAMDOWN);
        options.set(Parser.EXTENSIONS, Arrays.asList(
                AbbreviationExtension.create(),
                DefinitionExtension.create(),
                FootnoteExtension.create(),
                TablesExtension.create(),
                TypographicExtension.create()
        ));

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        Node document = parser.parse("This is *Sparta*");
        renderer.render(document);  // "<p>This is <em>Sparta</em></p>\n"
    }
```

**Comment by vsch** [comment]
@mnlipp, I did not include extensions as part of the profile because that would create a dependency between core and extensions. It is possible to create a separate profile module like was done for pegdown but it seems like overkill to include an extra 5 lines.

**Comment by mnlipp** [comment]
Okay, I get the idea now. But I think you underestimate the knowledge required to write those 5 lines.

A programmer who simply needs an e.g. kramdown compliant markdown processor has to analyze both kramdown's features and the available flexmark extensions to come up with the option list. Obviously, you have the knowledge readily available. It is documented now (above) for kramdown and the current version. But what if I need the complete options for some other markup flavor? What if the required options for a flavor change in a future version?

So, it might be overkill from your point of view. But I think it would be nice for the "casual" user to have  profile modules. Some factory implementation that provides the required MutableDataSet would be quite sufficient as content. And aside from saving 5 lines of code, such a profile module would also save the programmer from having to enumerate the core module and extension modules required in the build system -- a single dependency on the profile module (that provides the core module and the required extension modules as transient dependencies) would be sufficient.

**Comment by vsch** [comment]
@mnlipp, I can easily add a Kramdown profile module however it would also require some knowledge to know that it exists because it will not be part of the core functionality.

Alternately I can add documentation for kramdown compatibility then either solution will work. I already added this to the usability sample under Kramdown.

Where did you get the information on setting Kramdown compatibility mode? It would be the best place to add this information (kramdown profile module or extension list).

**Comment by mnlipp** [comment]
I think I got the idea about the profiles from your basic usage sample. There, commented out, is shown how to get the options from the ParserEmulationProfile. It never came to my mind that this covers only part of the required configuration.

However, my use case is not really kramdown. I'm writing a new version of a javadoc doclet that supports markdown. My idea was to offer the user the possibility to configure his favourite markdown flavour. I thought that would be as easy as selecting the matching value from ParserEmulationProfile. Now I understand that in addition, I need to configure the proper set of extensions for each flavour. So, I'd need a complete example for every flavor (or have to figure it out myself, of course).

**Comment by vsch** [comment]
@mnlipp, one thing to keep in mind is that other than CommonMark and Pegdown the other compatibility profiles have some compatibility discrepancies due to architectural parser differences.

The greatest is with GitHub Doc markdown. It has really weird list indentation parsing rules that I was not able to reverse engineer or implement in this parsing architecture for malformed input.

If you are converting the markdown to HTML then you don't need to worry about what the other parsers implement and just add all the extensions that you think will be useful and document these additions.

The profile only really makes a difference for list indentation processing. Most extensions do not use the profile and offer a standard behaviour that can be tweaked with their options.

As far as:

> So, I'd need a complete example for every flavor (or have to figure it out myself, of course).

It is either you or me. :D 

My use was mostly pegdown which I knew very well because my plugin relied on it heavily. CommonMark has a testable spec and this project started from a pure CommonMark parser so it is easy. The rest was a nightmare to get some compatibility tested because there is no spec and I spent hours with [BabelMark 2](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+item+1%0A+*+item+2%0A++*+item+3%0A+++*+item+4%0A++++*+item+5%0A+++++*+item+6%0A++++++*+item+7%0A+++++++*+item+8%0A++++++++*+item+9%0A)

After I got compatibility acceptably close, I got fed up with the minutia and figured that if someone does wind up using it and finds a discrepancy then it will be reported. If no one uses it then the point is moot and there is no point in putting more effort into it.

**Comment by mnlipp** [comment]
I admit that I hadn't given much thought to the different markup languages and their relationship up to now. I think what would have helped me is some additional information in section "Markdown Processor Emulation". Maybe like this:

> Despite its name, commonmark is neither a superset nor a subset of other markdown flavors. 
> Rather, it proposes a standard, unambiguous syntax specification for the original, "core" Markdown, 
> thus effectively introducing yet another flavor. While flexmark is by default commonmark compliant,
> its parser can be tweaked in various ways. The sets of tweaks required to emulate the most commonly
> used markdown parsers around are available in flexmark as `ParserEmulationProfile`s.
> 
> As the name `ParserEmulationProfile` implies, it's only the parser that is adjusted to the specific
> markdown flavor. Applying the profile does not add features beyond those available in commonmark.
> If you want to use flexmark to fully emulate another markdown processor's behavior, you have to
> adjust the parser _and_ configure the flexmark extensions that provide the additional features
> available in the parser that you want to emulate.

Having a better understanding now, I'll handle my doclet configuration differently. I'll default to
commonmark syntax (with the option for the user to change that) and add those extensions that
make sense in the context (e.g. footnotes don't).

**Comment by vsch** [comment]
@mnlipp, thank you for the suggestion. it is a good summary. I will add it.
