### ISSUE TITLE
support markdown to confluence markup converter

### ISSUE THREAD

**Issue by NargiT** [vsch/flexmark-java#71]
Would be nice to have support for this, and go further in order to implement also code markup.

Code block : https://confluence.atlassian.com/doc/code-block-macro-139390.html
Confluence wiki markup : https://confluence.atlassian.com/doc/confluence-wiki-markup-251003035.html

**Comment by vsch** [comment]
@NargiT, the jira-converter will do the conversion but if you find some discrepancies then please report them so I can address them. 

My knowledge of confluence is limited. If you find an incorrect conversion and know what it should be please include this information.

**Comment by NargiT** [comment]
Hello,

Let's assume I'll start by creating a new class
```java
com.vladsch.flexmark.confluence

public class ConfluenceRender implement IRender
```

Is this the good way to start ?

**Comment by vsch** [comment]
@NargiT, I would recommend taking the `flexmark-jira-converter` module which is really confluence with limitations needed for JIRA comments and modifying the `JiraConverterNodeRenderer` to add all the nodes which are handled by other extensions that implement their own "JIRA" output type.

Keep the type as "JIRA" since the two are compatible just change the rendering. This would be the easiest way to proceed since all the supporting boiler plate code is in place.

It will allow you to get started and focus on the conversion rather than the flexmark-java implementation details and give you a smoother learning curve.

There is some documentation for the parser architecture in [Writing Extensions](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions). I am not very good at writing documentation because I learn interactively by working with code: modifying and debugging it.

Extensions that handle their own "JIRA" rendering are:

* `flexmark-ext-emoji`
* `flexmark-ext-ins`
* `flexmark-ext-gfm-strikethrough`
* `flexmark-ext-superscript`
* `flexmark-ext-tables`
* `flexmark-ext-wikilink`

You should copy the node registration and node rendering from their NodeRenderer classes into your renderer. This way it will handle all rendering giving you full control.

Starting with a class implementing `IRender` interface is an option but you are starting from scratch and have no way to proceed without understanding all the necessary details. If you want to take this route you should look at `flexmark-formatter` which implements `IRender` and support code needed for rendering non-html output, in this case Markdown.

I don't know what you use as your dev environment but I would highly recommend [IntelliJ](https://www.jetbrains.com/idea/), either Ultimate or Community Edition. I use both interchangeably on this project. Its navigation, completions and find usages go a long way in helping figure our foreign code.

**Comment by NargiT** [comment]
The problem by using the current version of jira is that confluence does not use exactly the same output in order to process some field. 

For example table are not render the same way, because confluence uses macros in order to allow sorting by column at "runtime"

```html
<h3 class="auto-cursor-target">Tables</h3>
<table>
<colgroup><col /><col /><col /><col /></colgroup>
<tbody>
<tr>
<th>Header 1</th>
<th>Header 2</th>
<th>Header 3</th>
<th>Header 4</th></tr>
<tr>
<td>Cell 1 row 1</td>
<td>Cell 2 row 1</td>
<td>Cell 3 row 1</td>
<td>Cell 4 row 1</td></tr>
<tr>
<td>Cell 1 row 2</td>
<td>Cell 2 row 2</td>
<td>Cell 3 row 2</td>
<td>Cell 4 row 2</td></tr></tbody></table>
```

There is also the "code" macro

<h3 class="auto-cursor-target">Tables</h3>
<table><colgroup><col /><col /><col /><col /></colgroup>
<tbody>
<tr>
<th>Header 1</th>
<th>Header 2</th>
<th>Header 3</th>
<th>Header 4</th></tr>
<tr>
<td>Cell 1 row 1</td>
<td>Cell 2 row 1</td>
<td>Cell 3 row 1</td>
<td>Cell 4 row 1</td></tr>
<tr>
<td>Cell 1 row 2</td>
<td>Cell 2 row 2</td>
<td>Cell 3 row 2</td>
<td>Cell 4 row 2</td></tr></tbody></table>
<h3>Bullet points</h3>
<ul>
<li>bullet 1</li>
<li>bullet 2</li>
<li>bullet 3</li></ul>
<p><br /></p>
<h3>Date</h3>
<p><time datetime="2017-03-16" />&nbsp;</p>

```xml
<h3>Code</h3>
<ac:structured-macro ac:name="code" ac:schema-version="1" ac:macro-id="441f7c74-d0f6-4e41-864c-d82cd60836ac">
<ac:parameter ac:name="language">java</ac:parameter>
<ac:plain-text-body>
<![CDATA[
public static int main(String[] args) {
  // this is java code
}]]>
</ac:plain-text-body>
</ac:structured-macro>
```

Whereas jira table have a different output '|' and the code is panel is not as powerfull as confluence one.

**Comment by vsch** [comment]
@NargiT, in this case you can still start with JIRA module as a boiler-plate of extension code. For rendering start with the CoreNodeRenderer from the `flexmark` module to get control of all core nodes. Copy the custom node rendering code that generates HTML to your renderer from extensions that you want to support into your confluence renderer. 

Starting with the HTML rendering is closer to what you want than JIRA. 

Your node renderer can register any node classes it will handle. If your extension is the first in the list of extensions then its renderer will be used for these nodes giving you full control of how they are rendered.

The test resources in most modules contain the `...spec_ast.md` files which are combined Markdown, generated HTML and AST of the parsed result. This is a good place to understand the AST for all Markdown constructs, including the Node class names which are used in the AST as the node name.

Here is an example of a test case:

    ```````````````````````````````` example Extra tests: 7
    - item 
      - sub item  
    with lazy continuation
    .
    <ul>
      <li>item
        <ul>
          <li>sub item<br />
          with lazy continuation</li>
        </ul>
      </li>
    </ul>
    .
    Document[0, 46]
      BulletList[0, 46] isTight
        BulletListItem[0, 46] open:[0, 1, "-"] isTight
          Paragraph[2, 8]
            Text[2, 6] chars:[2, 6, "item"]
          BulletList[10, 46] isTight
            BulletListItem[10, 46] open:[10, 11, "-"] isTight
              Paragraph[12, 46]
                Text[12, 20] chars:[12, 20, "sub item"]
                HardLineBreak[20, 23]
                Text[23, 45] chars:[23, 45, "with  … ation"]
    ````````````````````````````````
