### ISSUE TITLE
Space in link

### ISSUE THREAD

**Issue by robinshine** [vsch/flexmark-java#78]
Looks like flexmark does not accept spaces on links (even use GitHub markdown profile)

For instance:
[sometext](some file)

While GitHub flavored markup supports it.

**Comment by vsch** [comment]
@robinshine, this is one difference that GitHub Doc has that the emulation does not handle. GitHub only allows it in documents but no longer in comments. Comments have been migrated to CommonMark syntax.

Spaces need to be URL encoded: [sometext](some%20file) to make it parse correctly

I will take a look at the link parsing to see if it can be changed to allow spaces in links with a configuration option.

**Comment by vsch** [comment]
@robinshine, just tested a link with a space in a GitHub document and it was not recognized as a link. https://github.com/vsch/GitHubWikiTest/blob/master/Test.md

However, I tested adding spaces to explicit link address characters and seems to work but may result in some parsing weirdness. I only have basic tests for links with spaces. Use it with well formed Markdown. Don't break link address with a space across lines. It will not be recognized. Line break before a title is allowed as per CommonMark rules.

I will add the option to allow spaces in links but it will be disabled by default and if you want this then you will need to set it explicitly in the options you pass to `Parser.builder()`

Here is the version comment:

* Add: #78, Space in link, option `Parser.SPACE_IN_LINK_URLS`, default `false`. When enabled
  will allow spaces in link address as long as they are not followed by a `"`, used to start the
  title of the link. Link address wrapped in `<>` will include any trailing spaces.

  Auto-links, wrapped or not in `<>` cannot have spaces. These require URL encoding the space
  with `%20`.

**Comment by vsch** [comment]
@robinshine, repo updated. Maven com.vladsch.flexmark:flexmark-java:0.18.3 released. Use this option if you really feel you need spaces in links.

**Comment by robinshine** [comment]
@vsch Thanks for the quick turnaround. I tested and it works like a charm!

BTW: AST with source information available is really helpful. I can easily create an extension to make users changing task status simply by checking/unchecking task item without needing to actually edit the markup.

**Comment by vsch** [comment]
@robinshine, you are welcome. 

The AST source tracking was a must have because the library was created to replace pegdown parser in my [Markdown Navigator](https://vladsch.com/product/markdown-navigator) plugin for IntelliJ IDEA and the rest of their excellent IDEs.

pegdown's source information was limited to node start, end offset. To properly syntax highlight parts of a node I had to re-parse each node's text and keep track of the resulting offsets. Very, very error prone, hard to debug, hard to test and a PITA to maintain. I wanted to avoid this at any cost.

In flexmark-java, I went a step further by making all text in the AST have source offset information, if it is derived from the source input. 

This simplifies getting source information about a part of the node's text to manipulating it as represented by `BasedSequence` extension of `CharSequence`, and then getting the offsets from the result. You can `subSequence(start, end).trim()` for example, then get the offsets without worrying about the details of how the preceding text manipulations are mapped to offset operations. 

Saying that this approach is a lot simpler than doing the text manipulation and tracking the offsets in parallel is an understatement. 

Enjoy the library and let me know if there is something missing or you can't find an elegant solution to a problem for your use case.
