### ISSUE TITLE
Documentation for AST manipulation

### ISSUE THREAD

**Issue by zergin** [vsch/flexmark-java#85]
Hello, I'm trying to manipulate AST to programaticly add metadata to parsed documents. There seems to be no example/documentation/test/source that would be a reference for inserting new content into AST. 

The closest I found was AutoLink extension that inserted new Link nodes but this still used `BasedSequence` from original content. How would one add a completely new link to a document w/o matching `BasedSequence` (which completely lacks any documentation)? All `Node`s require `BasedSequce` in all metchods.

Should I create an extension? A `PostProcessor`? What if I need to process entire document to analyse it and only later manipulate AST (so `ParserExtension` wouldn't have enough data...)? 

Anything would be useful. Even the simplest example, given:
```
Some markdown content.
```
how would one add a link to "markdown" so it points to documentation and when reformatted would yield:
```
Some [markdown](http://commonmark.org) content.
```

**Comment by vsch** [comment]
ample that has both regex text based search link creation and one that will append arbitrary markdown text to the document by parsing it as a separate document and then transferring its nodes to the end of original document.

[SyntheticLinkSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/SyntheticLinkSample.java)

In it you can see how to create a `BasedSequence` which does not contain any part of original input string but still has an offset into it by using a `PrefixedSubSequence` for the inserted text with an empty sub sequence from the original input text.

The regex based link post processor uses the original text as the link text and inserted string for the link URL.

In the sample the `markdown` string is hard coded and so is the URL but you can easily make this configurable and select the URL based on the matched string.

**Comment by vsch** [comment]
The sample for input 

    Some markdown content.

results in output:

    <p>Some <a href="http://commonmark.org">markdown</a> content</p>
    <p>Some inserted text with a link <a href="https://github.com/vsch/flexmark-java">flexmark-java</a> in paragraph.</p>

**Comment by vsch** [comment]
@zergin, I misread your request and gave you a sample that will generate the HTML instead of a formatting sample.

Here is a formatter extension that does the same thing as the previous sample but generates the markdown:

[SyntheticLinkFormatterSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/SyntheticLinkFormatterSample.java)

This is a lot simpler than HTML generation because you don't need to modify the AST but the node formatter for Text nodes. You can add other nodes but should use the [CoreNodeFormatter](https://github.com/vsch/flexmark-java/blob/master/flexmark-formatter/src/main/java/com/vladsch/flexmark/formatter/internal/CoreNodeFormatter.java) node rendering as a starting point for other nodes.

The sample for input

    Some markdown content.

results in output:

    Some [markdown](http://commonmark.org) content
    
    Some inserted text with a link [flexmark-java](https://github.com/vsch/flexmark-java) in paragraph.

**Comment by zergin** [comment]
Great! Both samples are extremely helpful and are more then enough to get me started. This is what I was missing - much appreciated, thank you.
