### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by kiru** [vsch/flexmark-java#9]
I'd like to use this in my project to have the same result as the Markdown Navigator plugin.

I don't see this plugin on the maven repository? Do you plan to publish it there?

Is there any simple example code to generate a html output for given markdown file?

**Comment by vsch** [comment]
@kiru, I have not setup the project at maven central. I was focused on getting it complete and releasing the plugin first. Now that it is done I will work on getting it released on maven central.

If you want I can make a jar for you of all the modules and give you the sample code to setup all the options that the plugin uses to setup the parser/renderer.

Default parser/renderer configuration is commonmark compliant which does not work well for GFM.

Let me know if you want the jar or will wait for the maven central release. It might take a few days since I have to add rudimentary javadocs to all the classes.

**Comment by kiru** [comment]
@vsch Thank you for the quick reply. I can wait for the maven realease. Don't hurry, take your time to.
